extends Node3D
## Reads park_data.json (generated by convert_to_godot.py) and builds:
##   • One flat ribbon MeshInstance3D per highway type (batched for performance)
##   • One StaticBody3D with BoxShape3D collision per boundary segment (invisible walls)

const DATA_PATH := "res://park_data.json"
const BIN_PATH  := "res://park_data.bin"
const PATH_Y    := 0.06   # metres above ground plane
const WATER_Y   := 0.03   # water sits above ground, below path ribbons
var _tex_cache:    Dictionary = {}   # path → ImageTexture (null if missing)
var _shader_cache: Dictionary = {}   # key  → compiled Shader (reused across materials)

# Heightmap for snapping geometry to the rendered terrain surface
var _hm_data:       Array   = []
var _hm_width:      int     = 0
var _hm_depth:      int     = 0
var _hm_world_size: float   = 5000.0
var _hm_texture:    ImageTexture  # GPU-side heightmap for vertex shader snapping
var _hm_min_h:      float   = 0.0
var _hm_max_h:      float   = 1.0

# Cached furniture GLB meshes — loaded once, shared by _build_furniture + _build_trash_cans
var _furn_glb_meshes: Dictionary = {}


# Slope threshold for furniture placement
const BENCH_MAX_SLOPE := 0.27  # tan(~15°) — skip benches on steeper terrain

# Exposed for day/night cycle (main.gd writes emission at runtime)
var facade_materials: Array = []  # ShaderMaterial list for night window emission

# World atlas: unified 8192×8192 RG8 texture (R=surface type, G=occupancy bitmask)
# Replaces: splat_map, boundary bitmap, 5 dictionary grids
var _atlas_data: PackedByteArray   # raw RG8 bytes
var _atlas_res: int = 0            # atlas width/height (square)

var boundary_polygon: PackedVector2Array  # XZ boundary for player clamping
var landuse_zones: Array = []             # from park_data.json: type, name, points
var _bridge_outlines: Array = []          # bridge outline polygons for deck shapes
var _tunnel_outlines: Array = []          # tunnel outline polygons for labels

var water_bodies: Array = []              # water body polygons for shore blending
var _water_polygons: Array = []           # water polygon outlines for proximity baking
var _canopy_texture: ImageTexture         # 2K canopy coverage map for dappled shade
var _water_builder                        # water_builder.gd instance
var _building_builder                     # building_builder.gd instance
var _tree_builder                        # tree_builder.gd instance
var _boundary_builder                    # boundary_builder.gd instance
var _furniture_builder                   # furniture_builder.gd instance
var _infrastructure_builder              # infrastructure_builder.gd instance
var _gap_builder                         # gap_builder.gd instance
var _grass_builder                       # grass_builder.gd instance
var _path_builder                        # path_builder.gd instance


# ---------------------------------------------------------------------------
# World atlas queries — surface type and occupancy from unified RG8 texture
# ---------------------------------------------------------------------------
func _atlas_surface(wx: float, wz: float) -> int:
	## Returns the atlas R channel (surface type) at world position (wx, wz).
	## 0=outside, 1=grass, 2=paved, 3=unpaved, 4=water, 5=building, 6=bridge, 7=rock.
	if _atlas_data.is_empty():
		return 0
	var half := _hm_world_size * 0.5
	var scale := float(_atlas_res) / _hm_world_size
	var px := int((wx + half) * scale)
	var pz := int((wz + half) * scale)
	if px < 0 or px >= _atlas_res or pz < 0 or pz >= _atlas_res:
		return 0
	return _atlas_data[(pz * _atlas_res + px) * 2]

func _atlas_occupancy(wx: float, wz: float) -> int:
	## Returns the atlas G channel (occupancy bitmask) at world position (wx, wz).
	if _atlas_data.is_empty():
		return 0
	var half := _hm_world_size * 0.5
	var scale := float(_atlas_res) / _hm_world_size
	var px := int((wx + half) * scale)
	var pz := int((wz + half) * scale)
	if px < 0 or px >= _atlas_res or pz < 0 or pz >= _atlas_res:
		return 0
	return _atlas_data[(pz * _atlas_res + px) * 2 + 1]

func _is_on_path(wx: float, wz: float) -> bool:
	## Returns true if the atlas surface at (wx, wz) is paved (2) or unpaved (3).
	var s := _atlas_surface(wx, wz)
	return s == 2 or s == 3


func _load_world_atlas() -> void:
	## Load world_atlas.bin (8-byte header + RG8 data) into _atlas_data.
	var fh := FileAccess.open("res://world_atlas.bin", FileAccess.READ)
	if not fh:
		push_warning("ParkLoader: world_atlas.bin not found — run convert_to_godot.py first")
		return
	var w := fh.get_32()
	var h := fh.get_32()
	if w != h or w < 1:
		push_warning("ParkLoader: world_atlas.bin invalid header: %d×%d" % [w, h])
		fh.close()
		return
	_atlas_res = w
	_atlas_data = fh.get_buffer(w * h * 2)
	fh.close()
	# Count surface types for diagnostics
	var counts := PackedInt32Array()
	counts.resize(8)
	counts.fill(0)
	for i in range(w * h):
		var s: int = _atlas_data[i * 2]
		if s < 8:
			counts[s] += 1
	print("ParkLoader: world atlas %d×%d loaded — grass=%d path=%d water=%d building=%d bridge=%d" % [
		w, h, counts[1], counts[2] + counts[3], counts[4], counts[5], counts[6]])


# ---------------------------------------------------------------------------
# Typed helpers – avoids Dictionary.get() returning Variant (parse error in 4.6)
# ---------------------------------------------------------------------------
func _hw_width(hw: String) -> float:
	match hw:
		"pedestrian": return 12.0  # Mall / Literary Walk ~40ft
		"footway":    return 3.5
		"cycleway":   return 3.5
		"steps":      return 3.0
		"track":      return 3.0
		"service":    return 8.0   # Park loop drives
		"secondary":  return 10.0  # Transverse roads
		"bridleway":  return 3.5   # Bridle paths
		_:            return 2.5   # "path" and unknowns


func _path_width(path: Dictionary) -> float:
	## Returns path width using: explicit OSM width > named overrides > highway default.
	var w = path.get("width", 0)
	if w is float and w > 0.0:
		return w
	if w is int and w > 0:
		return float(w)
	if w is String and w != "":
		var wf := float(w)
		if wf > 0.0:
			return wf
	return _hw_width(str(path.get("highway", "path")))


func _hw_y_priority(hw: String) -> float:
	## Higher-priority paths render on top at crossings.
	match hw:
		"pedestrian": return 0.05
		"footway":    return 0.04
		"steps":      return 0.03
		"cycleway":   return 0.02
		"path":       return 0.01
		"track":      return 0.00
		_:            return 0.01


func _hw_render_priority(hw: String) -> int:
	match hw:
		"pedestrian": return 5
		"footway":    return 4
		"steps":      return 3
		"cycleway":   return 2
		"path":       return 1
		"track":      return 0
		_:            return 1


func _path_color(hw: String, surface: String) -> Color:
	# Surface tag takes priority; highway type is the fallback
	match surface:
		"asphalt":            return Color(0.28, 0.28, 0.30)   # dark grey tarmac
		"concrete":           return Color(0.68, 0.68, 0.66)   # light grey concrete
		"concrete:plates":    return Color(0.65, 0.65, 0.63)   # concrete slabs
		"paving_stones":      return Color(0.78, 0.74, 0.65)   # cream/buff stone pavers
		"sett":               return Color(0.54, 0.52, 0.48)   # grey stone setts
		"unhewn_cobblestone": return Color(0.52, 0.50, 0.44)   # rough cobble
		"pebblestone":        return Color(0.60, 0.57, 0.50)   # pebble stone
		"stone":              return Color(0.60, 0.58, 0.54)   # cut stone
		"rock":               return Color(0.56, 0.54, 0.50)   # bare rock
		"brick":              return Color(0.68, 0.38, 0.26)   # brick red
		"metal":              return Color(0.62, 0.63, 0.66)   # steel grating
		"wood":               return Color(0.50, 0.34, 0.16)   # wooden boardwalk
		"paved":              return Color(0.60, 0.60, 0.58)   # generic paved
		"compacted":          return Color(0.52, 0.42, 0.28)   # compressed dirt/gravel
		"fine_gravel":        return Color(0.64, 0.57, 0.44)   # fine gravel
		"gravel":             return Color(0.60, 0.53, 0.40)   # loose gravel
		"unpaved":            return Color(0.54, 0.43, 0.28)   # unpaved dirt
		"dirt":               return Color(0.50, 0.38, 0.22)   # bare dirt
		"ground":             return Color(0.46, 0.38, 0.26)   # natural ground
		"grass":              return Color(0.28, 0.52, 0.18)   # grass path
		"woodchips":          return Color(0.46, 0.32, 0.14)   # woodchip mulch
		"mulch":              return Color(0.40, 0.28, 0.12)   # dark mulch
		"sand":               return Color(0.76, 0.70, 0.52)   # sand
		"tartan":             return Color(0.58, 0.32, 0.22)   # reddish-brown cinder track
	# Fallback to highway type
	match hw:
		"footway":    return Color(0.72, 0.68, 0.58)   # buff paving stone
		"cycleway":   return Color(0.30, 0.30, 0.32)   # asphalt
		"pedestrian": return Color(0.24, 0.24, 0.25)   # dark gray asphalt (Mall promenade per Wikimedia)
		"path":       return Color(0.60, 0.53, 0.40)   # gravel trail
		"steps":      return Color(0.60, 0.58, 0.54)   # grey stone
		"track":      return Color(0.48, 0.40, 0.26)   # brown dirt track
		"bridleway":  return Color(0.52, 0.42, 0.28)   # compacted earth
		"service":    return Color(0.26, 0.26, 0.28)   # dark asphalt (park drives)
		"secondary":  return Color(0.28, 0.28, 0.30)   # dark grey asphalt (streets)
		_:            return Color(0.60, 0.53, 0.40)   # gravel


# ---------------------------------------------------------------------------
# Geometry helpers — miter normals & box posts
# ---------------------------------------------------------------------------

func _compute_miter_normals(pts: Array, n_pts: int) -> Array[Vector2]:
	## Compute miter bisector normals for a polyline. Returns Array of Vector2.
	var miter: Array[Vector2] = []
	miter.resize(n_pts)
	for mi in range(n_pts):
		var nvp := Vector2.ZERO
		var nvn := Vector2.ZERO
		if mi > 0:
			var sp := Vector2(float(pts[mi][0]) - float(pts[mi-1][0]),
							  float(pts[mi][2]) - float(pts[mi-1][2]))
			if sp.length_squared() > 0.0001:
				var dp := sp.normalized()
				nvp = Vector2(-dp.y, dp.x)
		if mi < n_pts - 1:
			var sn := Vector2(float(pts[mi+1][0]) - float(pts[mi][0]),
							  float(pts[mi+1][2]) - float(pts[mi][2]))
			if sn.length_squared() > 0.0001:
				var dn := sn.normalized()
				nvn = Vector2(-dn.y, dn.x)
		if nvp.length_squared() < 0.0001:
			miter[mi] = nvn
		elif nvn.length_squared() < 0.0001:
			miter[mi] = nvp
		else:
			var bisect := nvp + nvn
			if bisect.length_squared() < 0.0001:
				miter[mi] = nvn
			else:
				bisect = bisect.normalized()
				var cos_half := bisect.dot(nvn)
				if cos_half < 0.5:
					cos_half = 0.5
				miter[mi] = bisect / cos_half
	return miter


func _add_box_post(v: PackedVector3Array, n: PackedVector3Array,
				   cx: float, cz: float, bot_y: float, top_y: float,
				   post_w: float) -> void:
	## Append a 4-face box post (no top/bottom) to non-indexed vertex/normal arrays.
	var hw := post_w * 0.5
	var hy := (top_y - bot_y) * 0.5
	var cy := bot_y + hy
	var faces := [
		[Vector3(cx+hw,cy-hy,cz+hw), Vector3(cx+hw,cy-hy,cz-hw), Vector3(cx+hw,cy+hy,cz-hw), Vector3(cx+hw,cy+hy,cz+hw), Vector3(1,0,0)],
		[Vector3(cx-hw,cy-hy,cz-hw), Vector3(cx-hw,cy-hy,cz+hw), Vector3(cx-hw,cy+hy,cz+hw), Vector3(cx-hw,cy+hy,cz-hw), Vector3(-1,0,0)],
		[Vector3(cx-hw,cy-hy,cz+hw), Vector3(cx+hw,cy-hy,cz+hw), Vector3(cx+hw,cy+hy,cz+hw), Vector3(cx-hw,cy+hy,cz+hw), Vector3(0,0,1)],
		[Vector3(cx+hw,cy-hy,cz-hw), Vector3(cx-hw,cy-hy,cz-hw), Vector3(cx-hw,cy+hy,cz-hw), Vector3(cx+hw,cy+hy,cz-hw), Vector3(0,0,-1)],
	]
	for face in faces:
		var f0: Vector3 = face[0]; var f1: Vector3 = face[1]
		var f2: Vector3 = face[2]; var f3: Vector3 = face[3]
		var fn: Vector3 = face[4]
		v.append_array(PackedVector3Array([f0, f1, f2, f0, f2, f3]))
		for _j in range(6):
			n.append(fn)


# ---------------------------------------------------------------------------
# Texture helpers
# ---------------------------------------------------------------------------
func _load_tex(path: String) -> ImageTexture:
	if path in _tex_cache:
		return _tex_cache[path]
	if not FileAccess.file_exists(path):
		_tex_cache[path] = null
		return null
	var img := Image.load_from_file(path)
	if not img:
		_tex_cache[path] = null
		return null
	img.generate_mipmaps()
	var tex := ImageTexture.create_from_image(img)
	_tex_cache[path] = tex
	return tex


func _get_shader(key: String, code_or_path: String) -> Shader:
	if key in _shader_cache:
		return _shader_cache[key]
	var sh: Shader
	if code_or_path.begins_with("res://") and code_or_path.ends_with(".gdshader"):
		sh = load(code_or_path) as Shader
	else:
		sh = Shader.new()
		sh.code = code_or_path
	_shader_cache[key] = sh
	return sh


func _make_mesh(verts: PackedVector3Array, normals: PackedVector3Array,
				uvs = null, colors = null, indices = null) -> ArrayMesh:
	## Build an ArrayMesh from packed arrays. Accepts optional UVs, colors, indices.
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals
	if uvs != null:
		arrays[Mesh.ARRAY_TEX_UV] = uvs
	if colors != null:
		arrays[Mesh.ARRAY_COLOR] = colors
	if indices != null:
		arrays[Mesh.ARRAY_INDEX] = indices
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return mesh


func _path_tex_prefix(hw: String, surface: String) -> String:
	match surface:
		"asphalt":                              return "res://textures/Asphalt012_2K-JPG"
		"concrete", "concrete:plates", "paved": return "res://textures/Concrete034_2K-JPG"
		"paving_stones", "sett", "unhewn_cobblestone", \
		"stone", "brick":                       return "res://textures/PavingStones130_2K-JPG"
		"gravel", "fine_gravel", "compacted", "pebblestone", \
		"unpaved", "dirt", "ground", "woodchips", \
		"mulch", "sand", "tartan":              return "res://textures/Gravel021_2K-JPG"
		"wood":                                 return "res://textures/WoodFloor041_2K-JPG"
	match hw:
		"cycleway":   return "res://textures/Asphalt012_2K-JPG"
		"steps":      return "res://textures/Concrete034_2K-JPG"
		"pedestrian": return "res://textures/Asphalt012_2K-JPG"  # Mall promenade
		"footway":    return "res://textures/PavingStones130_2K-JPG"
		"service":    return "res://textures/Asphalt012_2K-JPG"
		"secondary":  return "res://textures/Asphalt012_2K-JPG"
		_:            return "res://textures/Gravel021_2K-JPG"


func _make_bridge_deck_material(hw: String, surface: String) -> Material:
	## Like path material but with terrain-snapping disabled (bridge decks are pre-elevated).
	## Uses the path shader so bridge decks get rain, snow, and seasonal effects.
	var prefix  := _path_tex_prefix(hw, surface)
	var tex_alb := _load_tex(prefix + "_Color.jpg")
	var tex_nrm := _load_tex(prefix + "_NormalGL.jpg")
	var tex_rgh := _load_tex(prefix + "_Roughness.jpg")
	var mat := ShaderMaterial.new()
	mat.shader = _get_shader("path", _path_shader_code())
	if tex_alb:
		mat.set_shader_parameter("tex_alb", tex_alb)
	if tex_nrm:
		mat.set_shader_parameter("tex_nrm", tex_nrm)
	if tex_rgh:
		mat.set_shader_parameter("tex_rgh", tex_rgh)
	mat.set_shader_parameter("tint", _path_color(hw, surface))
	mat.set_shader_parameter("snap_to_terrain", 0.0)  # no terrain snap for bridge decks
	if _canopy_texture:
		mat.set_shader_parameter("canopy_map", _canopy_texture)
	return mat


func _make_path_material(hw: String, surface: String) -> Material:
	var prefix  := _path_tex_prefix(hw, surface)
	var tex_alb := _load_tex(prefix + "_Color.jpg")
	var tex_nrm := _load_tex(prefix + "_NormalGL.jpg")
	var tex_rgh := _load_tex(prefix + "_Roughness.jpg")
	# Always use the shader path so vertex-shader terrain snapping works
	var mat        := ShaderMaterial.new()
	mat.shader      = _get_shader("path", _path_shader_code())
	if tex_alb:
		mat.set_shader_parameter("tex_alb", tex_alb)
	if tex_nrm:
		mat.set_shader_parameter("tex_nrm", tex_nrm)
	if tex_rgh:
		mat.set_shader_parameter("tex_rgh", tex_rgh)
	mat.set_shader_parameter("tint",    _path_color(hw, surface))
	mat.set_shader_parameter("path_y_offset", PATH_Y + _hw_y_priority(hw))
	mat.render_priority = _hw_render_priority(hw)
	# Canopy coverage map for dappled shade
	if _canopy_texture:
		mat.set_shader_parameter("canopy_map", _canopy_texture)
	# Heightmap for vertex-shader terrain snapping
	if _hm_texture:
		mat.set_shader_parameter("heightmap_tex", _hm_texture)
		mat.set_shader_parameter("hm_world_size", _hm_world_size)
		mat.set_shader_parameter("hm_min_h",      _hm_min_h)
		mat.set_shader_parameter("hm_range",      _hm_max_h - _hm_min_h)
		mat.set_shader_parameter("hm_res",        float(mini(_hm_width, 4096)))
	return mat


func _path_shader_code() -> String:
	return "res://shaders/path.gdshader"


func _make_curb_material() -> Material:
	## Granite curb material — terrain-snapped with per-vertex height offset.
	## Shared by all paved path curbs (single draw call for all curbs).
	var mat := ShaderMaterial.new()
	mat.shader = _get_shader("curb", "res://shaders/curb.gdshader")
	mat.set_shader_parameter("curb_top_offset", PATH_Y + 0.04)  # average hw priority
	mat.set_shader_parameter("curb_below_grade", 0.04)
	if _hm_texture:
		mat.set_shader_parameter("heightmap_tex", _hm_texture)
		mat.set_shader_parameter("hm_world_size", _hm_world_size)
		mat.set_shader_parameter("hm_min_h",      _hm_min_h)
		mat.set_shader_parameter("hm_range",      _hm_max_h - _hm_min_h)
		mat.set_shader_parameter("hm_res",        float(mini(_hm_width, 4096)))
	return mat


# ---------------------------------------------------------------------------
# Canopy coverage map — 2K grayscale Image stamped from placed tree crowns.
# Used by terrain + path shaders for dappled sunlight through tree canopy.
# ---------------------------------------------------------------------------
func _generate_canopy_map(data: Array) -> ImageTexture:
	const CANOPY_RES := 2048
	# Use raw byte array for speed — Image.get_pixel/set_pixel is slow in hot loops
	var buf := PackedByteArray()
	buf.resize(CANOPY_RES * CANOPY_RES)
	buf.fill(0)

	var half := _hm_world_size * 0.5
	var cell_m := _hm_world_size / float(CANOPY_RES)

	for entry in data:
		var wx: float = entry["x"]
		var wz: float = entry["z"]
		var cr: float = entry["r"]  # crown radius in metres

		# Convert to pixel coordinates
		var px := int((wx + half) / cell_m)
		var pz := int((wz + half) / cell_m)
		var pr := int(ceil(cr / cell_m))  # radius in pixels
		if pr < 1:
			pr = 1
		var r_sq := float(pr * pr)
		var inv_r := 1.0 / float(pr)

		# Stamp a soft circle (quadratic falloff) directly on byte buffer
		var y0 := maxi(pz - pr, 0)
		var y1 := mini(pz + pr, CANOPY_RES - 1)
		var x0 := maxi(px - pr, 0)
		var x1 := mini(px + pr, CANOPY_RES - 1)
		for iy in range(y0, y1 + 1):
			var dy := iy - pz
			var dy2 := float(dy * dy)
			var row := iy * CANOPY_RES
			for ix in range(x0, x1 + 1):
				var dx := ix - px
				var dist_sq := dy2 + float(dx * dx)
				if dist_sq > r_sq:
					continue
				var t := sqrt(dist_sq) * inv_r
				var intensity := int((1.0 - t * t) * 178.0)  # 0.7 * 255 ≈ 178
				var idx := row + ix
				buf[idx] = mini(buf[idx] + intensity, 255)

	var img := Image.create_from_data(CANOPY_RES, CANOPY_RES, false, Image.FORMAT_L8, buf)
	var tex := ImageTexture.create_from_image(img)
	print("Canopy map: %d trees → %d×%d coverage texture" % [data.size(), CANOPY_RES, CANOPY_RES])
	return tex


# ---------------------------------------------------------------------------
# Heightmap terrain sampler — matches the bilinear interpolation used by the
# terrain mesh in main.gd so paths/water sit exactly on the rendered surface.
# ---------------------------------------------------------------------------
func set_heightmap(data: Array, width: int, depth: int, world_size: float) -> void:
	## Receive pre-loaded heightmap data from main.gd (avoids double-parsing JSON).
	_hm_data       = data
	_hm_width      = width
	_hm_depth      = depth
	_hm_world_size = world_size
	_build_hm_gpu_texture()


func _build_hm_gpu_texture() -> void:
	## Load pre-baked GPU heightmap texture, or compute at runtime as fallback.
	## Format: 4096×4096 RG8 (16-bit encoded heights, R=high byte, G=low byte).
	if _hm_data.is_empty():
		return

	# Try pre-baked binary first (generated by convert_to_godot.py)
	if FileAccess.file_exists("res://heightmap_gpu.bin"):
		var fh := FileAccess.open("res://heightmap_gpu.bin", FileAccess.READ)
		var tex_w := fh.get_32()
		var tex_h := fh.get_32()
		_hm_min_h = fh.get_float()
		_hm_max_h = fh.get_float()
		var buf := fh.get_buffer(tex_w * tex_h * 2)
		fh.close()
		var img := Image.create_from_data(tex_w, tex_h, false, Image.FORMAT_RG8, buf)
		_hm_texture = ImageTexture.create_from_image(img)
		print("ParkLoader: heightmap GPU texture loaded %d×%d (h_range=%.1f)" % [
			tex_w, tex_h, _hm_max_h - _hm_min_h])
		return

	# Fallback: compute at runtime from 8K heightmap data
	_hm_min_h = INF; _hm_max_h = -INF
	for v in _hm_data:
		var fv := float(v)
		_hm_min_h = minf(_hm_min_h, fv)
		_hm_max_h = maxf(_hm_max_h, fv)
	var h_range := maxf(_hm_max_h - _hm_min_h, 0.01)
	var tex_w := mini(_hm_width, 4096)
	var tex_h := mini(_hm_depth, 4096)
	var sx := float(_hm_width - 1) / float(tex_w - 1)
	var sz := float(_hm_depth - 1) / float(tex_h - 1)
	var data := PackedByteArray()
	data.resize(tex_w * tex_h * 2)
	for zi in tex_h:
		var hzi := mini(int(zi * sz + 0.5), _hm_depth - 1)
		for xi in tex_w:
			var hxi := mini(int(xi * sx + 0.5), _hm_width - 1)
			var h := (float(_hm_data[hzi * _hm_width + hxi]) - _hm_min_h) / h_range
			var h16 := int(clampf(h, 0.0, 1.0) * 65535.0)
			var off := (zi * tex_w + xi) * 2
			data[off]     = h16 >> 8     # high byte → R
			data[off + 1] = h16 & 0xFF   # low byte → G
	var img := Image.create_from_data(tex_w, tex_h, false, Image.FORMAT_RG8, data)
	_hm_texture = ImageTexture.create_from_image(img)
	print("ParkLoader: heightmap GPU texture computed %d×%d (h_range=%.1f)" % [
		tex_w, tex_h, h_range])


func _terrain_y(x: float, z: float) -> float:
	## Sample the heightmap at world (x, z) using the SAME triangle interpolation
	## as the terrain mesh in main.gd.  The mesh splits each quad along the
	## i00→i11 diagonal (bottom-left to top-right), giving two triangles:
	##   T1 (fz <= fx): i00, i10, i11
	##   T2 (fz >  fx): i00, i11, i01
	## Using bilinear would give different heights between grid points and cause
	## paths to float above or clip through the rendered terrain.
	if _hm_data.is_empty():
		return 0.0
	var half := _hm_world_size * 0.5
	var xi   := (x + half) / _hm_world_size * (_hm_width  - 1)
	var zi   := (z + half) / _hm_world_size * (_hm_depth  - 1)
	var xi0  := clampi(int(xi), 0, _hm_width  - 2)
	var zi0  := clampi(int(zi), 0, _hm_depth  - 2)
	var fx   := xi - xi0
	var fz   := zi - zi0
	var h00  := float(_hm_data[zi0       * _hm_width + xi0    ])
	var h10  := float(_hm_data[zi0       * _hm_width + xi0 + 1])
	var h01  := float(_hm_data[(zi0 + 1) * _hm_width + xi0    ])
	var h11  := float(_hm_data[(zi0 + 1) * _hm_width + xi0 + 1])
	# Barycentric interpolation matching the mesh diagonal i00→i11
	if fz <= fx:
		# Lower-right triangle: i00(0,0), i10(1,0), i11(1,1)
		return h00 + (h10 - h00) * fx + (h11 - h10) * fz
	else:
		# Upper-left triangle: i00(0,0), i11(1,1), i01(0,1)
		return h00 + (h11 - h01) * fx + (h01 - h00) * fz



# ---------------------------------------------------------------------------
# CPU-side value noise / FBM — matches shader hash2/vnoise/fbm exactly
# ---------------------------------------------------------------------------
func _hash2(p: Vector2) -> float:
	var q := Vector2(fmod(abs(p.x * 127.1), 1.0), fmod(abs(p.y * 311.7), 1.0))
	# replicate fract(p * vec2(127.1, 311.7))
	q = Vector2(p.x * 127.1 - floor(p.x * 127.1), p.y * 311.7 - floor(p.y * 311.7))
	var d := q.x * (q.x + 43.21) + q.y * (q.y + 43.21) + q.x * q.y
	q += Vector2(d, d)  # p += dot(p, p + 43.21)
	var v := q.x * q.y
	return v - floor(v)


func _vnoise(p: Vector2) -> float:
	var i := Vector2(floor(p.x), floor(p.y))
	var f := Vector2(p.x - floor(p.x), p.y - floor(p.y))
	var u := Vector2(f.x * f.x * (3.0 - 2.0 * f.x), f.y * f.y * (3.0 - 2.0 * f.y))
	var h00 := _hash2(i)
	var h10 := _hash2(Vector2(i.x + 1.0, i.y))
	var h01 := _hash2(Vector2(i.x, i.y + 1.0))
	var h11 := _hash2(Vector2(i.x + 1.0, i.y + 1.0))
	return lerp(lerp(h00, h10, u.x), lerp(h01, h11, u.x), u.y)


func _fbm(p: Vector2, octaves: int) -> float:
	var v := 0.0
	var a := 0.5
	var q := p
	for _i in octaves:
		v += a * _vnoise(q)
		q *= 2.13
		a *= 0.47
	return v


func _in_boundary(px: float, pz: float) -> bool:
	## O(1) atlas lookup — inside park if surface type > 0.
	return _atlas_surface(px, pz) > 0


static func _convex_hull(points: PackedVector2Array) -> PackedVector2Array:
	## Andrew's monotone chain — returns convex hull in CCW order.
	if points.size() < 3:
		return points
	var pts: Array = []
	for p in points:
		pts.append(p)
	pts.sort_custom(func(a: Vector2, b: Vector2) -> bool:
		return a.x < b.x or (a.x == b.x and a.y < b.y))
	var lower: Array = []
	for p in pts:
		while lower.size() >= 2:
			var a: Vector2 = lower[lower.size() - 2]
			var b: Vector2 = lower[lower.size() - 1]
			if (b - a).cross(p - a) <= 0.0:
				lower.pop_back()
			else:
				break
		lower.append(p)
	var upper: Array = []
	for i in range(pts.size() - 1, -1, -1):
		var p: Vector2 = pts[i]
		while upper.size() >= 2:
			var a: Vector2 = upper[upper.size() - 2]
			var b: Vector2 = upper[upper.size() - 1]
			if (b - a).cross(p - a) <= 0.0:
				upper.pop_back()
			else:
				break
		upper.append(p)
	# Remove last point of each half because it repeats
	lower.pop_back()
	upper.pop_back()
	var result := PackedVector2Array()
	for p in lower:
		result.append(p)
	for p in upper:
		result.append(p)
	return result


# ---------------------------------------------------------------------------
# Binary park data reader (CPW1 format — much faster than JSON)
# ---------------------------------------------------------------------------
func _read_string_table(fa: FileAccess) -> PackedStringArray:
	var count := fa.get_16()
	var out := PackedStringArray()
	out.resize(count)
	for i in count:
		var slen := fa.get_16()
		out[i] = fa.get_buffer(slen).get_string_from_utf8()
	return out


func _load_park_data_bin() -> Dictionary:
	if not FileAccess.file_exists(BIN_PATH):
		return {}
	var fa := FileAccess.open(BIN_PATH, FileAccess.READ)
	if fa == null:
		return {}
	var magic := fa.get_buffer(4)
	if magic != PackedByteArray([0x43, 0x50, 0x57, 0x31]):  # "CPW1"
		fa.close()
		return {}
	var _version := fa.get_32()
	var sect_count := fa.get_32()

	# Read section directory
	var sections: Dictionary = {}
	for _i in sect_count:
		var tag := fa.get_buffer(4).get_string_from_ascii()
		var sec_off := fa.get_32()
		var sec_size := fa.get_32()
		sections[tag] = [sec_off, sec_size]

	var data: Dictionary = {}

	# -- META section (JSON blob with scalars + small sections) ----
	if sections.has("META"):
		fa.seek(sections["META"][0])
		var json_len := fa.get_32()
		var json_str := fa.get_buffer(json_len).get_string_from_utf8()
		var meta = JSON.parse_string(json_str)
		if typeof(meta) == TYPE_DICTIONARY:
			for key in meta:
				data[key] = meta[key]

	# -- BNDY section (boundary polygon) ----
	if sections.has("BNDY"):
		fa.seek(sections["BNDY"][0])
		var count := fa.get_32()
		var coords := fa.get_buffer(count * 8).to_float32_array()
		var boundary: Array = []
		boundary.resize(count)
		for i in count:
			boundary[i] = [coords[i * 2], coords[i * 2 + 1]]
		data["boundary"] = boundary

	# -- TREE section (columnar) ----
	if sections.has("TREE"):
		fa.seek(sections["TREE"][0])
		var count := fa.get_32()
		if count > 0:
			var sp_table := _read_string_table(fa)
			var positions := fa.get_buffer(count * 12).to_float32_array()
			# Read uint16 arrays manually since Godot lacks to_uint16_array
			var sp_idx := PackedInt32Array()
			sp_idx.resize(count)
			for i in count:
				sp_idx[i] = fa.get_16()
			var dbh := PackedInt32Array()
			dbh.resize(count)
			for i in count:
				dbh[i] = fa.get_16()
			var lidar_h := fa.get_buffer(count * 4).to_float32_array()
			var crown_a := fa.get_buffer(count * 4).to_float32_array()
			var trees: Array = []
			trees.resize(count)
			for i in count:
				trees[i] = {
					"pos": [positions[i * 3], positions[i * 3 + 1], positions[i * 3 + 2]],
					"species": sp_table[sp_idx[i]],
					"dbh": dbh[i],
					"lidar_h": lidar_h[i],
					"crown_a": crown_a[i],
				}
			data["trees"] = trees
		else:
			data["trees"] = []

	# -- BLDG section (columnar) ----
	if sections.has("BLDG"):
		fa.seek(sections["BLDG"][0])
		var count := fa.get_32()
		if count > 0:
			var total_pts := fa.get_32()
			var all_pts := fa.get_buffer(total_pts * 8).to_float32_array()
			var offsets := fa.get_buffer(count * 4).to_int32_array()
			var pt_counts := PackedInt32Array()
			pt_counts.resize(count)
			for i in count:
				pt_counts[i] = fa.get_16()
			var heights := fa.get_buffer(count * 4).to_float32_array()
			var bases := fa.get_buffer(count * 4).to_float32_array()
			var ground_elevs := fa.get_buffer(count * 4).to_float32_array()
			var years := PackedInt32Array()
			years.resize(count)
			for i in count:
				years[i] = fa.get_16()
			var floors := PackedInt32Array()
			floors.resize(count)
			for i in count:
				floors[i] = fa.get_16()
			var bin_table := _read_string_table(fa)
			var bin_idx := PackedInt32Array()
			bin_idx.resize(count)
			for i in count:
				bin_idx[i] = fa.get_16()
			var name_table := _read_string_table(fa)
			var name_idx := PackedInt32Array()
			name_idx.resize(count)
			for i in count:
				name_idx[i] = fa.get_16()
			var buildings: Array = []
			buildings.resize(count)
			for i in count:
				var npts := pt_counts[i]
				var off := offsets[i]
				var pts: Array = []
				pts.resize(npts)
				for j in npts:
					pts[j] = [all_pts[(off + j) * 2], all_pts[(off + j) * 2 + 1]]
				buildings[i] = {
					"points": pts,
					"height": heights[i],
					"base": bases[i],
					"ground_elev": ground_elevs[i],
					"year_built": years[i],
					"num_floors": floors[i],
					"bin": bin_table[bin_idx[i]],
					"name": name_table[name_idx[i]],
				}
			data["buildings"] = buildings
		else:
			data["buildings"] = []

	# -- PATH section (columnar) ----
	if sections.has("PATH"):
		fa.seek(sections["PATH"][0])
		var count := fa.get_32()
		if count > 0:
			var hw_table := _read_string_table(fa)
			var surf_table := _read_string_table(fa)
			var name_table := _read_string_table(fa)
			var total_pts := fa.get_32()
			var all_pts := fa.get_buffer(total_pts * 12).to_float32_array()
			var offsets := fa.get_buffer(count * 4).to_int32_array()
			var pt_counts := PackedInt32Array()
			pt_counts.resize(count)
			for i in count:
				pt_counts[i] = fa.get_16()
			var hw_idx := PackedInt32Array()
			hw_idx.resize(count)
			for i in count:
				hw_idx[i] = fa.get_16()
			var surf_idx := PackedInt32Array()
			surf_idx.resize(count)
			for i in count:
				surf_idx[i] = fa.get_16()
			var name_idx := PackedInt32Array()
			name_idx.resize(count)
			for i in count:
				name_idx[i] = fa.get_16()
			var paths: Array = []
			paths.resize(count)
			for i in count:
				var npts := pt_counts[i]
				var off := offsets[i]
				var pts: Array = []
				pts.resize(npts)
				for j in npts:
					var bi := (off + j) * 3
					pts[j] = [all_pts[bi], all_pts[bi + 1], all_pts[bi + 2]]
				paths[i] = {
					"highway": hw_table[hw_idx[i]],
					"surface": surf_table[surf_idx[i]],
					"points": pts,
					"name": name_table[name_idx[i]],
				}
			data["paths"] = paths
		else:
			data["paths"] = []

	# -- BARR section (columnar) ----
	if sections.has("BARR"):
		fa.seek(sections["BARR"][0])
		var count := fa.get_32()
		if count > 0:
			var type_table := _read_string_table(fa)
			var mat_table := _read_string_table(fa)
			var total_pts := fa.get_32()
			var all_pts := fa.get_buffer(total_pts * 12).to_float32_array()
			var offsets := fa.get_buffer(count * 4).to_int32_array()
			var pt_counts := PackedInt32Array()
			pt_counts.resize(count)
			for i in count:
				pt_counts[i] = fa.get_16()
			var type_idx := PackedInt32Array()
			type_idx.resize(count)
			for i in count:
				type_idx[i] = fa.get_16()
			var barr_heights := fa.get_buffer(count * 4).to_float32_array()
			var mat_idx := PackedInt32Array()
			mat_idx.resize(count)
			for i in count:
				mat_idx[i] = fa.get_16()
			var barriers: Array = []
			barriers.resize(count)
			for i in count:
				var npts := pt_counts[i]
				var off := offsets[i]
				var pts: Array = []
				pts.resize(npts)
				for j in npts:
					var bi := (off + j) * 3
					pts[j] = [all_pts[bi], all_pts[bi + 1], all_pts[bi + 2]]
				barriers[i] = {
					"type": type_table[type_idx[i]],
					"height": barr_heights[i],
					"points": pts,
					"material": mat_table[mat_idx[i]],
				}
			data["barriers"] = barriers
		else:
			data["barriers"] = []

	# -- BNCH section (flat float array) ----
	if sections.has("BNCH"):
		fa.seek(sections["BNCH"][0])
		var count := fa.get_32()
		var benches: Array = []
		if count > 0:
			var buf := fa.get_buffer(count * 16).to_float32_array()
			benches.resize(count)
			for i in count:
				benches[i] = [buf[i * 4], buf[i * 4 + 1], buf[i * 4 + 2], buf[i * 4 + 3]]
		data["benches"] = benches

	# -- LAMP section (flat float array) ----
	if sections.has("LAMP"):
		fa.seek(sections["LAMP"][0])
		var count := fa.get_32()
		var lamps: Array = []
		if count > 0:
			var buf := fa.get_buffer(count * 12).to_float32_array()
			lamps.resize(count)
			for i in count:
				lamps[i] = [buf[i * 3], buf[i * 3 + 1], buf[i * 3 + 2]]
		data["lampposts"] = lamps

	# -- TRSH section (flat float array) ----
	if sections.has("TRSH"):
		fa.seek(sections["TRSH"][0])
		var count := fa.get_32()
		var cans: Array = []
		if count > 0:
			var buf := fa.get_buffer(count * 12).to_float32_array()
			cans.resize(count)
			for i in count:
				cans[i] = [buf[i * 3], buf[i * 3 + 1], buf[i * 3 + 2]]
		data["trash_cans"] = cans

	# -- FLAG section (flat float array) ----
	if sections.has("FLAG"):
		fa.seek(sections["FLAG"][0])
		var count := fa.get_32()
		var poles: Array = []
		if count > 0:
			var buf := fa.get_buffer(count * 12).to_float32_array()
			poles.resize(count)
			for i in count:
				poles[i] = [buf[i * 3], buf[i * 3 + 1], buf[i * 3 + 2]]
		data["flagpoles"] = poles

	fa.close()
	return data


# ---------------------------------------------------------------------------
func _ready() -> void:
	# Heightmap data is passed via set_heightmap() before add_child().
	# Build GPU texture if not already done (fallback for standalone testing).
	if _hm_texture == null and not _hm_data.is_empty():
		_build_hm_gpu_texture()

	# Try binary format first (2-5× faster), fall back to JSON
	var _t_load := Time.get_ticks_msec()
	var data: Dictionary = _load_park_data_bin()
	if not data.is_empty():
		print("ParkLoader: loaded park_data.bin in %d ms" % (Time.get_ticks_msec() - _t_load))
	else:
		if not FileAccess.file_exists(DATA_PATH):
			push_warning("ParkLoader: park_data.json not found – run convert_to_godot.py first")
			return
		var fa := FileAccess.open(DATA_PATH, FileAccess.READ)
		data = JSON.parse_string(fa.get_as_text())
		fa.close()
		if typeof(data) != TYPE_DICTIONARY:
			push_error("ParkLoader: failed to parse park_data.json")
			return
		print("ParkLoader: loaded park_data.json in %d ms" % (Time.get_ticks_msec() - _t_load))

	# Populate boundary polygon FIRST so all builders can clip to it.
	# Use convex hull to eliminate transverse-road pinch points in OSM boundary.
	var raw_boundary: Array = data.get("boundary", [])
	if raw_boundary.size() >= 3:
		var raw_poly := PackedVector2Array()
		raw_poly.resize(raw_boundary.size())
		for i in range(raw_boundary.size()):
			raw_poly[i] = Vector2(float(raw_boundary[i][0]), float(raw_boundary[i][1]))
		boundary_polygon = _convex_hull(raw_poly)
		# Subdivide long segments so facades/walls get dense building blocks
		var subdiv := PackedVector2Array()
		var max_seg := 15.0  # metres — matches facade 30m block logic
		for i in range(boundary_polygon.size()):
			var p1 := boundary_polygon[i]
			var p2 := boundary_polygon[(i + 1) % boundary_polygon.size()]
			subdiv.append(p1)
			var d := p1.distance_to(p2)
			if d > max_seg:
				var steps := int(ceilf(d / max_seg))
				for s in range(1, steps):
					subdiv.append(p1.lerp(p2, float(s) / float(steps)))
		boundary_polygon = subdiv
		print("ParkLoader: boundary convex hull %d -> %d points (subdivided)" % [raw_poly.size(), boundary_polygon.size()])
	_load_world_atlas()

	# Cache data arrays once — avoids repeated Dictionary.get() calls
	var paths: Array = data.get("paths", [])
	var water: Array = data.get("water", [])
	water_bodies = water
	var trees: Array = data.get("trees", [])
	var buildings: Array = data.get("buildings", [])
	var barriers: Array = data.get("barriers", [])
	var statues: Array = data.get("statues", [])
	var benches: Array = data.get("benches", [])
	var lampposts: Array = data.get("lampposts", [])
	var trash_cans: Array = data.get("trash_cans", [])
	var flagpoles: Array = data.get("flagpoles", [])

	var shrubbery: Array = data.get("shrubbery", [])
	# Build boundary array from subdivided hull for walls/perimeter
	var boundary: Array = []
	for p in boundary_polygon:
		boundary.append([p.x, p.y])
	landuse_zones = data.get("landuse", [])
	_bridge_outlines = data.get("bridge_outlines", [])
	_tunnel_outlines = data.get("tunnel_outlines", [])

	var streams: Array = data.get("streams", [])
	var amenities: Array = data.get("amenities", [])
	var playgrounds: Array = data.get("playgrounds", [])
	var facilities: Array = data.get("facilities", [])
	var viewpoints: Array = data.get("viewpoints", [])
	var attractions: Array = data.get("attractions", [])

	_water_builder = preload("res://water_builder.gd").new(self)
	_building_builder = preload("res://building_builder.gd").new(self)
	_tree_builder = preload("res://tree_builder.gd").new(self)
	_boundary_builder = preload("res://boundary_builder.gd").new(self)
	_furniture_builder = preload("res://furniture_builder.gd").new(self)
	_infrastructure_builder = preload("res://infrastructure_builder.gd").new(self)
	_gap_builder = preload("res://gap_builder.gd").new(self)
	_grass_builder = preload("res://grass_builder.gd").new(self)
	_path_builder = preload("res://path_builder.gd").new(self)

	var _t0 := Time.get_ticks_msec()
	var _tp := _t0

	# --- Labels (informational text only) ---
	_boundary_builder._label_boundary_buildings(buildings)
	_build_bridge_tunnel_labels(paths)
	_infrastructure_builder._build_labels(water)
	_infrastructure_builder._build_facilities(facilities)
	_infrastructure_builder._build_viewpoints(viewpoints)
	_infrastructure_builder._build_attractions(attractions)
	_infrastructure_builder._build_gardens()  # labels only (hedge geometry removed)
	_infrastructure_builder._build_meadow_labels()
	_infrastructure_builder._build_special_zone_labels()
	_gap_builder._build_gap_markers()
	print("  labels: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()

	# --- Blender GLB models (data-positioned) ---
	_build_bridge_models()
	print("  bridge models: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()
	_tree_builder._build_trees(trees)
	print("  trees: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()
	_canopy_texture = _generate_canopy_map(_tree_builder.canopy_data)
	print("  canopy map: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()
	_grass_builder._build_grass()
	print("  grass: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()
	_furniture_builder._build_furniture(benches, lampposts, paths)
	_furniture_builder._build_trash_cans(trash_cans, paths)
	_furniture_builder._build_flagpoles(flagpoles)
	print("  furniture: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()
	_infrastructure_builder._build_statues(statues)
	_infrastructure_builder._build_amenities(amenities)  # GLB drinking fountains + labels
	_infrastructure_builder._build_bethesda_terrace()
	_infrastructure_builder._build_belvedere_castle()
	_infrastructure_builder._build_comfort_stations(amenities)
	_infrastructure_builder._build_vanderbilt_gate()
	_infrastructure_builder._build_bandshell()
	_infrastructure_builder._build_pergola()
	_infrastructure_builder._build_ladies_pavilion()
	_infrastructure_builder._build_cherry_hill_fountain()
	_infrastructure_builder._build_summerhouse()
	_infrastructure_builder._build_model_boathouse()
	_infrastructure_builder._build_boat_landings()
	_infrastructure_builder._build_cop_cot()
	_infrastructure_builder._build_imagine_mosaic()
	_infrastructure_builder._build_tennis_house()
	_infrastructure_builder._build_maintenance_yard()
	_infrastructure_builder._build_dana_pier()
	_infrastructure_builder._build_stone_weirs()
	_infrastructure_builder._build_rustic_bridges()
	_infrastructure_builder._build_dog_run_fences(landuse_zones)
	_infrastructure_builder._build_park_signs(paths)
	_infrastructure_builder._build_reservoir_fence(water)
	_infrastructure_builder._build_bridle_posts(paths)
	_infrastructure_builder._build_playground_equipment(landuse_zones)
	print("  statues+amenities: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()
	_infrastructure_builder._build_barriers(barriers)
	print("  barriers: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()
	_infrastructure_builder._build_sport_markings(landuse_zones)
	print("  sport markings: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()
	_infrastructure_builder._build_staircases(paths)
	print("  staircases: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()

	# --- Water surfaces (dynamic shader effect positioned by data) ---
	_water_builder._build_water(water)
	_water_builder._build_streams(streams)
	print("  water: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()

	# --- Boundary collision + perimeter wall ---
	_boundary_builder._build_boundary(boundary)
	_boundary_builder._build_perimeter_wall(boundary, paths)
	print("  boundary+wall: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()

	# --- Buildings (procedural — restored for visual context) ---
	_building_builder._build_buildings(buildings)
	print("  buildings: %d ms" % (Time.get_ticks_msec() - _tp)); _tp = Time.get_ticks_msec()

	print("ParkLoader: done in %d ms total" % (Time.get_ticks_msec() - _t0))



# ---------------------------------------------------------------------------
# Bridge / tunnel labels — geometry now baked into 8K LiDAR terrain mesh
# Bridge 3D models placed on top of bare earth DEM terrain
# ---------------------------------------------------------------------------

## Map of bridge name → GLB filename (models/furniture/)
const BRIDGE_GLBS: Dictionary = {
	"Bow Bridge": "cp_bow_bridge.glb",
	"Gapstow Bridge": "cp_gapstow_bridge.glb",
	"Greyshot Arch": "cp_greyshot_arch.glb",
	"Winterdale Arch": "cp_winterdale_arch.glb",
	"Dalehead Arch": "cp_dalehead_arch.glb",
	"Trefoil Arch": "cp_trefoil_arch.glb",
	"Huddlestone Arch": "cp_huddlestone_arch.glb",
	"Glen Span Arch": "cp_glen_span_arch.glb",
	"Springbanks Arch": "cp_springbanks_arch.glb",
	"Willowdell Arch": "cp_willowdell_arch.glb",
	"Driprock Arch": "cp_driprock_arch.glb",
	"Denesmouth Arch": "cp_denesmouth_arch.glb",
	"Green Gap Arch": "cp_green_gap_arch.glb",
	"Riftstone Arch": "cp_riftstone_arch.glb",
	"Balcony Bridge": "cp_balcony_bridge.glb",
	"Oak Bridge": "cp_oak_bridge.glb",
	"Eaglevale Bridge": "cp_eaglevale_bridge.glb",
}


func _build_bridge_models() -> void:
	## Load and place bridge GLB models at positions from bridge_outlines.
	## Each model was built with origin at deck center, bridge along Y axis.
	## We compute centroid + principal axis from the outline polygon, then
	## rotate the model to align with the real-world orientation.
	var count := 0
	var placed_names: Dictionary = {}
	var all_outlines: Array = []
	all_outlines.append_array(_bridge_outlines)
	all_outlines.append_array(_tunnel_outlines)
	for bo in all_outlines:
		var bname: String = bo.get("name", "")
		if bname.is_empty() or not BRIDGE_GLBS.has(bname) or placed_names.has(bname):
			continue
		var bpts: Array = bo.get("points", [])
		if bpts.size() < 3:
			continue

		# Centroid
		var cx := 0.0; var cy := 0.0; var cz := 0.0
		for pt in bpts:
			cx += float(pt[0]); cy += float(pt[1]); cz += float(pt[2])
		cx /= bpts.size(); cy /= bpts.size(); cz /= bpts.size()

		if not _in_boundary(cx, cz):
			continue

		# Use terrain height at centroid (bare earth DEM) as base,
		# but prefer the outline's average Y (from DSM) for deck height
		var ty := _terrain_y(cx, cz)
		# Use the outline Y which represents the deck surface height
		var deck_y := cy

		# Principal axis from covariance of outline XZ coordinates
		var cov_xx := 0.0; var cov_xz := 0.0; var cov_zz := 0.0
		for pt in bpts:
			var dx := float(pt[0]) - cx
			var dz := float(pt[2]) - cz
			cov_xx += dx * dx
			cov_xz += dx * dz
			cov_zz += dz * dz
		var angle := 0.5 * atan2(2.0 * cov_xz, cov_xx - cov_zz)

		# Load GLB as scene
		var glb_file: String = BRIDGE_GLBS[bname]
		var abs_path := ProjectSettings.globalize_path("res://models/furniture/" + glb_file)
		if not FileAccess.file_exists(abs_path):
			print("WARNING: bridge GLB not found: %s" % abs_path)
			continue

		var gltf_doc := GLTFDocument.new()
		var gltf_state := GLTFState.new()
		if gltf_doc.append_from_file(abs_path, gltf_state) != OK:
			print("WARNING: failed to load bridge GLB: %s" % abs_path)
			continue
		var root: Node3D = gltf_doc.generate_scene(gltf_state)
		if root == null:
			continue

		# Compute bounding extent along principal axis for collision
		var extent_major := 0.0
		var extent_minor := 0.0
		var cos_a := cos(angle)
		var sin_a := sin(angle)
		for pt in bpts:
			var dx := float(pt[0]) - cx
			var dz := float(pt[2]) - cz
			# Project onto principal axes
			var proj_major: float = absf(dx * cos_a + dz * sin_a)
			var proj_minor: float = absf(-dx * sin_a + dz * cos_a)
			extent_major = maxf(extent_major, proj_major)
			extent_minor = maxf(extent_minor, proj_minor)

		# Position at deck height, rotated to match outline principal axis
		# Blender bridge runs along Y → in Godot that's Z axis
		# angle is the principal axis direction in XZ plane
		root.position = Vector3(cx, deck_y, cz)
		root.rotation.y = -angle
		root.name = bname.replace(" ", "_")
		add_child(root)

		# Add walkable collision at deck level (box covering the outline footprint)
		var body := StaticBody3D.new()
		body.name = bname.replace(" ", "_") + "_col"
		var shape := BoxShape3D.new()
		# Major axis = bridge length (along Godot Z after rotation)
		# Minor axis = bridge width (along Godot X after rotation)
		shape.size = Vector3(extent_minor * 2, 0.5, extent_major * 2)
		var col := CollisionShape3D.new()
		col.shape = shape
		col.position = Vector3(0, -0.25, 0)  # top of box at deck surface
		body.add_child(col)
		body.position = Vector3(cx, deck_y, cz)
		body.rotation.y = -angle
		add_child(body)

		placed_names[bname] = true
		count += 1
		print("  Bridge model: %s at (%.0f, %.1f, %.0f) rot=%.1f° extent=%.0f×%.0f" % [
			bname, cx, deck_y, cz, rad_to_deg(-angle),
			extent_major * 2, extent_minor * 2])

	print("ParkLoader: bridge models = %d" % count)


func _build_bridge_tunnel_labels(paths: Array) -> void:
	# Collect named bridges from path data
	var labelled: Dictionary = {}
	for path in paths:
		var is_bridge: bool = path.get("bridge", false) or int(path.get("layer", 0)) >= 1
		if is_bridge:
			var bn: String = str(path.get("bridge_name", ""))
			if not bn.is_empty():
				labelled[bn] = true

	# Label named bridge/tunnel outlines
	for outlines in [_bridge_outlines, _tunnel_outlines]:
		for bo in outlines:
			var bname: String = bo.get("name", "")
			if bname.is_empty() or labelled.has(bname):
				continue
			var bpts: Array = bo.get("points", [])
			if bpts.size() < 3:
				continue
			var lx := 0.0; var lz := 0.0
			for pt in bpts:
				lx += float(pt[0]); lz += float(pt[2])
			lx /= bpts.size(); lz /= bpts.size()
			if not _in_boundary(lx, lz):
				continue
			var ly := _terrain_y(lx, lz) + 4.0
			var lbl := Label3D.new()
			lbl.text = bname
			lbl.font_size = 48
			lbl.pixel_size = 0.01
			lbl.billboard = BaseMaterial3D.BILLBOARD_ENABLED
			lbl.modulate = Color(0.75, 0.72, 0.68, 0.60)
			lbl.outline_modulate = Color(0.1, 0.1, 0.1, 0.50)
			lbl.outline_size = 8
			lbl.position = Vector3(lx, ly, lz)
			lbl.name = "Arch_Label"
			add_child(lbl)
			labelled[bname] = true




# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------
func _subdivide_pts(pts: Array, max_seg: float) -> Array:
	## Ensure no segment exceeds max_seg metres by inserting linearly interpolated points.
	var out: Array = [pts[0]]
	for i in range(1, pts.size()):
		var ax := float(pts[i-1][0]); var ay := float(pts[i-1][1]); var az := float(pts[i-1][2])
		var bx := float(pts[i][0]);   var by := float(pts[i][1]);   var bz := float(pts[i][2])
		var dx := bx - ax; var dz := bz - az
		var seg := sqrt(dx*dx + dz*dz)
		var n_sub := int(ceil(seg / max_seg))
		for j in range(1, n_sub + 1):
			var t := float(j) / float(n_sub)
			out.append([ax + dx * t, ay + (by - ay) * t, az + dz * t])
	return out


func _smooth_path_catmull_rom(pts: Array, subdiv: int = 4) -> Array:
	## Catmull-Rom spline through original nodes for smooth curves.
	## 'subdiv' interpolated segments between each pair of original points.
	if pts.size() < 3:
		return pts.duplicate()
	var out: Array = []
	for i in range(pts.size() - 1):
		var p0: Array = pts[max(i - 1, 0)]
		var p1: Array = pts[i]
		var p2: Array = pts[i + 1]
		var p3: Array = pts[min(i + 2, pts.size() - 1)]
		var x0 := float(p0[0]); var y0 := float(p0[1]); var z0 := float(p0[2])
		var x1 := float(p1[0]); var y1 := float(p1[1]); var z1 := float(p1[2])
		var x2 := float(p2[0]); var y2 := float(p2[1]); var z2 := float(p2[2])
		var x3 := float(p3[0]); var y3 := float(p3[1]); var z3 := float(p3[2])
		for j in subdiv:
			var t := float(j) / float(subdiv)
			var t2 := t * t
			var t3 := t2 * t
			var vx := 0.5 * ((2.0*x1) + (-x0+x2)*t + (2.0*x0-5.0*x1+4.0*x2-x3)*t2 + (-x0+3.0*x1-3.0*x2+x3)*t3)
			var vy := 0.5 * ((2.0*y1) + (-y0+y2)*t + (2.0*y0-5.0*y1+4.0*y2-y3)*t2 + (-y0+3.0*y1-3.0*y2+y3)*t3)
			var vz := 0.5 * ((2.0*z1) + (-z0+z2)*t + (2.0*z0-5.0*z1+4.0*z2-z3)*t2 + (-z0+3.0*z1-3.0*z2+z3)*t3)
			out.append([vx, vy, vz])
	out.append(pts[-1])
	return out


func _triangulate_polygon_2d(poly: PackedVector2Array) -> PackedInt32Array:
	## Ear-clipping triangulation for a simple polygon in 2D.
	## Returns index triplets into the original polygon.
	var indices := PackedInt32Array()
	var n := poly.size()
	if n < 3:
		return indices
	# Build index list
	var idx: Array[int] = []
	# Determine winding order (CCW = positive area)
	var area := 0.0
	for i in range(n):
		var j := (i + 1) % n
		area += poly[i].x * poly[j].y - poly[j].x * poly[i].y
	if area > 0.0:
		for i in range(n): idx.append(i)
	else:
		for i in range(n): idx.append(n - 1 - i)

	var remaining := idx.size()
	var fail_count := 0
	while remaining > 2 and fail_count < remaining * 2:
		for ei in range(remaining):
			if remaining <= 2:
				break
			var i0 := idx[(ei - 1 + remaining) % remaining]
			var i1 := idx[ei]
			var i2 := idx[(ei + 1) % remaining]
			var v0 := poly[i0]; var v1 := poly[i1]; var v2 := poly[i2]
			# Check if ear (convex vertex)
			var cross := (v1.x - v0.x) * (v2.y - v0.y) - (v1.y - v0.y) * (v2.x - v0.x)
			if cross <= 0.0:
				fail_count += 1
				continue
			# Check no other vertex inside this triangle
			var ear_ok := true
			for ci in range(remaining):
				var ci_idx := idx[ci]
				if ci_idx == i0 or ci_idx == i1 or ci_idx == i2:
					continue
				var p := poly[ci_idx]
				# Point-in-triangle test
				var d0 := (v1.x - v0.x) * (p.y - v0.y) - (v1.y - v0.y) * (p.x - v0.x)
				var d1 := (v2.x - v1.x) * (p.y - v1.y) - (v2.y - v1.y) * (p.x - v1.x)
				var d2 := (v0.x - v2.x) * (p.y - v2.y) - (v0.y - v2.y) * (p.x - v2.x)
				if d0 >= 0.0 and d1 >= 0.0 and d2 >= 0.0:
					ear_ok = false
					break
			if ear_ok:
				indices.append(i0)
				indices.append(i1)
				indices.append(i2)
				idx.remove_at(ei)
				remaining -= 1
				fail_count = 0
				break
			else:
				fail_count += 1
	return indices


func _project_onto_polyline(px: float, pz: float, pts: Array,
		cum_len: PackedFloat32Array) -> float:
	## Project a point onto a polyline and return the arc-length distance.
	var best_d := INF
	var best_t := 0.0
	for i in range(pts.size() - 1):
		var ax := float(pts[i][0]); var az := float(pts[i][2])
		var bx := float(pts[i+1][0]); var bz := float(pts[i+1][2])
		var dx := bx - ax; var dz := bz - az
		var seg_sq := dx * dx + dz * dz
		if seg_sq < 0.0001:
			continue
		var t := clampf(((px - ax) * dx + (pz - az) * dz) / seg_sq, 0.0, 1.0)
		var cx := ax + t * dx - px
		var cz := az + t * dz - pz
		var dist := cx * cx + cz * cz
		if dist < best_d:
			best_d = dist
			best_t = cum_len[i] + t * (cum_len[i + 1] - cum_len[i])
	return best_t



# Shared helper: PBR stone/concrete material — uses world-space UV so no
# UV array is needed on the mesh (works on parapets, portals, walls, etc.)
func _make_stone_material(alb: ImageTexture, nrm: ImageTexture, rgh: ImageTexture,
						  tint: Color) -> Material:
	if alb:
		var sm  := ShaderMaterial.new()
		sm.shader = _get_shader("stone", _stone_shader_code())
		sm.set_shader_parameter("tex_alb", alb)
		sm.set_shader_parameter("tex_nrm", nrm)
		sm.set_shader_parameter("tex_rgh", rgh)
		sm.set_shader_parameter("tint",    tint)
		return sm
	var mat        := StandardMaterial3D.new()
	mat.albedo_color = tint
	mat.roughness    = 0.88
	mat.cull_mode    = BaseMaterial3D.CULL_DISABLED
	return mat


func _stone_shader_code() -> String:
	return "res://shaders/stone.gdshader"




# ---------------------------------------------------------------------------
# GLB loading helpers — used by trees, rocks, furniture, etc.
# ---------------------------------------------------------------------------
func _collect_meshes(node: Node, out: Array, _depth: int = 0) -> void:
	if node is MeshInstance3D:
		out.append(node.mesh)
	for child in node.get_children():
		_collect_meshes(child, out, _depth + 1)


## Load a GLB file at runtime. Uses .res cache to skip GLTFDocument on repeat loads.
var _glb_cache: Dictionary = {}  # abs_path -> Dictionary of {mesh_name: Mesh}
func _load_glb_meshes(abs_path: String) -> Dictionary:
	if _glb_cache.has(abs_path):
		return _glb_cache[abs_path]
	var result: Dictionary = {}
	if not FileAccess.file_exists(abs_path):
		print("WARNING: GLB not found: %s" % abs_path)
		return result

	# Derive cache path from GLB filename
	var fname := abs_path.get_file().get_basename()
	var cache_dir := "res://cache/glb"
	var cache_meta := "%s/%s.txt" % [cache_dir, fname]

	# Try .res cache (much faster than GLTFDocument parsing)
	if FileAccess.file_exists(cache_meta):
		var glb_mod := FileAccess.get_modified_time(abs_path)
		var cache_mod := FileAccess.get_modified_time(ProjectSettings.globalize_path(cache_meta))
		if cache_mod >= glb_mod:
			var mfa := FileAccess.open(cache_meta, FileAccess.READ)
			var count := int(mfa.get_line())
			var names: Array = []
			for _i in count:
				names.append(mfa.get_line())
			mfa.close()
			var all_ok := true
			for i in count:
				var mpath := "%s/%s_%d.res" % [cache_dir, fname, i]
				if not ResourceLoader.exists(mpath):
					all_ok = false
					break
				result[names[i]] = ResourceLoader.load(mpath)
			if all_ok and result.size() == count:
				_glb_cache[abs_path] = result
				return result
			result.clear()

	# GLB loading (slow path — first run only)
	var gltf_doc := GLTFDocument.new()
	var gltf_state := GLTFState.new()
	var err := gltf_doc.append_from_file(abs_path, gltf_state)
	if err != OK:
		print("WARNING: failed to load GLB %s (error %d)" % [abs_path, err])
		return result
	var root: Node = gltf_doc.generate_scene(gltf_state)
	if root == null:
		return result
	_collect_named_meshes(root, result)
	root.queue_free()

	# Save to .res cache for next run
	if not result.is_empty():
		DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(cache_dir))
		var mfa := FileAccess.open(cache_meta, FileAccess.WRITE)
		mfa.store_line(str(result.size()))
		for mname in result:
			mfa.store_line(mname)
		mfa.close()
		var idx := 0
		for mname in result:
			ResourceSaver.save(result[mname], "%s/%s_%d.res" % [cache_dir, fname, idx])
			idx += 1
		print("GLB: cached %s (%d meshes)" % [fname, result.size()])
	_glb_cache[abs_path] = result
	return result


func _collect_named_meshes(node: Node, out: Dictionary) -> void:
	if node is MeshInstance3D and node.mesh != null:
		out[node.name] = node.mesh
	for child in node.get_children():
		_collect_named_meshes(child, out)


func _spawn_multimesh(mesh: Mesh, mat: Material,
					  transforms: Array, node_name: String) -> MultiMeshInstance3D:
	if transforms.is_empty():
		return null
	var mm             := MultiMesh.new()
	mm.transform_format = MultiMesh.TRANSFORM_3D
	mm.mesh             = mesh
	mm.instance_count   = transforms.size()
	for i in transforms.size():
		mm.set_instance_transform(i, transforms[i])
	var mmi              := MultiMeshInstance3D.new()
	mmi.multimesh         = mm
	mmi.name              = node_name
	if mat != null:
		mmi.material_override = mat
	add_child(mmi)
	return mmi



func _make_cylinder(radius: float, height: float, segments: int) -> ArrayMesh:
	var verts := PackedVector3Array()
	var normals := PackedVector3Array()
	for i in range(segments):
		var a0 := TAU * float(i) / float(segments)
		var a1 := TAU * float(i + 1) / float(segments)
		var x0 := cos(a0) * radius
		var z0 := sin(a0) * radius
		var x1 := cos(a1) * radius
		var z1 := sin(a1) * radius
		var hh := height * 0.5
		# Side quad (2 tris)
		var n0 := Vector3(cos(a0), 0, sin(a0)).normalized()
		var n1 := Vector3(cos(a1), 0, sin(a1)).normalized()
		verts.append(Vector3(x0, -hh, z0)); normals.append(n0)
		verts.append(Vector3(x1, -hh, z1)); normals.append(n1)
		verts.append(Vector3(x1, hh, z1)); normals.append(n1)
		verts.append(Vector3(x0, -hh, z0)); normals.append(n0)
		verts.append(Vector3(x1, hh, z1)); normals.append(n1)
		verts.append(Vector3(x0, hh, z0)); normals.append(n0)
		# Top cap tri
		verts.append(Vector3(0, hh, 0)); normals.append(Vector3.UP)
		verts.append(Vector3(x0, hh, z0)); normals.append(Vector3.UP)
		verts.append(Vector3(x1, hh, z1)); normals.append(Vector3.UP)
	var mesh := _make_mesh(verts, normals)
	return mesh




