extends Node3D
## Reads park_data.json (generated by convert_to_godot.py) and builds:
##   • One flat ribbon MeshInstance3D per highway type (batched for performance)
##   • One StaticBody3D with BoxShape3D collision per boundary segment (invisible walls)

const DATA_PATH := "res://park_data.json"
const HM_PATH   := "res://heightmap.json"
const PATH_Y    := 0.06   # metres above ground plane
const WATER_Y   := 0.03   # water sits above ground, below path ribbons

var _tex_cache: Dictionary = {}   # path → ImageTexture (null if missing)

# Heightmap for snapping geometry to the rendered terrain surface
var _hm_data:       Array   = []
var _hm_width:      int     = 0
var _hm_depth:      int     = 0
var _hm_world_size: float   = 5000.0


# ---------------------------------------------------------------------------
# Typed helpers – avoids Dictionary.get() returning Variant (parse error in 4.6)
# ---------------------------------------------------------------------------
func _hw_width(hw: String) -> float:
	match hw:
		"pedestrian": return 6.0
		"footway":    return 3.0
		"cycleway":   return 3.5
		"steps":      return 2.5
		"track":      return 3.0
		_:            return 2.5   # "path" and unknowns


func _path_color(hw: String, surface: String) -> Color:
	# Surface tag takes priority; highway type is the fallback
	match surface:
		"asphalt":            return Color(0.28, 0.28, 0.30)   # dark grey tarmac
		"concrete":           return Color(0.68, 0.68, 0.66)   # light grey concrete
		"concrete:plates":    return Color(0.65, 0.65, 0.63)   # concrete slabs
		"paving_stones":      return Color(0.78, 0.74, 0.65)   # cream/buff stone pavers
		"sett":               return Color(0.54, 0.52, 0.48)   # grey stone setts
		"unhewn_cobblestone": return Color(0.52, 0.50, 0.44)   # rough cobble
		"pebblestone":        return Color(0.60, 0.57, 0.50)   # pebble stone
		"stone":              return Color(0.60, 0.58, 0.54)   # cut stone
		"rock":               return Color(0.56, 0.54, 0.50)   # bare rock
		"brick":              return Color(0.68, 0.38, 0.26)   # brick red
		"metal":              return Color(0.62, 0.63, 0.66)   # steel grating
		"wood":               return Color(0.50, 0.34, 0.16)   # wooden boardwalk
		"paved":              return Color(0.60, 0.60, 0.58)   # generic paved
		"compacted":          return Color(0.52, 0.42, 0.28)   # compressed dirt/gravel
		"fine_gravel":        return Color(0.64, 0.57, 0.44)   # fine gravel
		"gravel":             return Color(0.60, 0.53, 0.40)   # loose gravel
		"unpaved":            return Color(0.54, 0.43, 0.28)   # unpaved dirt
		"dirt":               return Color(0.50, 0.38, 0.22)   # bare dirt
		"ground":             return Color(0.46, 0.38, 0.26)   # natural ground
		"grass":              return Color(0.28, 0.52, 0.18)   # grass path
		"woodchips":          return Color(0.46, 0.32, 0.14)   # woodchip mulch
		"mulch":              return Color(0.40, 0.28, 0.12)   # dark mulch
		"sand":               return Color(0.76, 0.70, 0.52)   # sand
	# Fallback to highway type
	match hw:
		"footway":    return Color(0.70, 0.64, 0.52)   # warm tan / gravel
		"cycleway":   return Color(0.30, 0.30, 0.32)   # asphalt (cycleways are almost always asphalt)
		"pedestrian": return Color(0.78, 0.74, 0.65)   # pale cream stone
		"path":       return Color(0.54, 0.44, 0.30)   # earthy dirt
		"steps":      return Color(0.60, 0.58, 0.54)   # grey stone
		"track":      return Color(0.48, 0.40, 0.26)   # brown dirt track
		_:            return Color(0.65, 0.60, 0.48)


# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# Texture helpers
# ---------------------------------------------------------------------------
func _load_tex(path: String) -> ImageTexture:
	if path in _tex_cache:
		return _tex_cache[path]
	if not FileAccess.file_exists(path):
		_tex_cache[path] = null
		return null
	var img := Image.load_from_file(path)
	if not img:
		_tex_cache[path] = null
		return null
	img.generate_mipmaps()
	var tex := ImageTexture.create_from_image(img)
	_tex_cache[path] = tex
	return tex


func _path_tex_prefix(hw: String, surface: String) -> String:
	match surface:
		"asphalt":                              return "res://textures/Asphalt012_1K-JPG"
		"concrete", "concrete:plates", "paved": return "res://textures/Concrete034_1K-JPG"
		"paving_stones", "sett", "unhewn_cobblestone", \
		"stone", "brick":                       return "res://textures/PavingStones130_1K-JPG"
		"gravel", "fine_gravel", "compacted", "pebblestone", \
		"unpaved", "dirt", "ground", "woodchips", \
		"mulch", "sand":                        return "res://textures/Gravel021_1K-JPG"
		"wood":                                 return "res://textures/WoodFloor041_1K-JPG"
	match hw:
		"cycleway":   return "res://textures/Asphalt012_1K-JPG"
		"steps":      return "res://textures/Concrete034_1K-JPG"
		"pedestrian": return "res://textures/PavingStones130_1K-JPG"
		"footway":    return "res://textures/PavingStones130_1K-JPG"
		_:            return "res://textures/Gravel021_1K-JPG"


func _make_path_material(hw: String, surface: String) -> Material:
	var prefix  := _path_tex_prefix(hw, surface)
	var tex_alb := _load_tex(prefix + "_Color.jpg")
	var tex_nrm := _load_tex(prefix + "_NormalGL.jpg")
	var tex_rgh := _load_tex(prefix + "_Roughness.jpg")
	if tex_alb == null:
		var mat        := StandardMaterial3D.new()
		mat.albedo_color = _path_color(hw, surface)
		mat.roughness    = 0.85
		mat.cull_mode    = BaseMaterial3D.CULL_DISABLED
		return mat
	var shader     := Shader.new()
	shader.code     = _path_shader_code()
	var mat        := ShaderMaterial.new()
	mat.shader      = shader
	mat.set_shader_parameter("tex_alb", tex_alb)
	mat.set_shader_parameter("tex_nrm", tex_nrm)
	mat.set_shader_parameter("tex_rgh", tex_rgh)
	mat.set_shader_parameter("tint",    _path_color(hw, surface))
	return mat


func _path_shader_code() -> String:
	return """shader_type spatial;
render_mode cull_disabled;

uniform sampler2D tex_alb : source_color,      filter_linear_mipmap_anisotropic, repeat_enable;
uniform sampler2D tex_nrm : hint_normal,        filter_linear_mipmap_anisotropic, repeat_enable;
uniform sampler2D tex_rgh : hint_default_white, filter_linear_mipmap_anisotropic, repeat_enable;
uniform vec4 tint : source_color = vec4(1.0);

void fragment() {
	vec3  alb   = texture(tex_alb, UV).rgb;
	float rough = texture(tex_rgh, UV).r;
	ALBEDO     = alb * tint.rgb;
	NORMAL_MAP = texture(tex_nrm, UV).rgb;
	ROUGHNESS  = clamp(rough * 0.9 + 0.05, 0.0, 1.0);
	METALLIC   = 0.0;
}
"""


# ---------------------------------------------------------------------------
# Heightmap terrain sampler — matches the bilinear interpolation used by the
# terrain mesh in main.gd so paths/water sit exactly on the rendered surface.
# ---------------------------------------------------------------------------
func _load_heightmap() -> void:
	if not FileAccess.file_exists(HM_PATH):
		return
	var fa := FileAccess.open(HM_PATH, FileAccess.READ)
	var hm  = JSON.parse_string(fa.get_as_text())
	fa.close()
	if typeof(hm) != TYPE_DICTIONARY:
		return
	_hm_width      = int(hm["width"])
	_hm_depth      = int(hm["depth"])
	_hm_world_size = float(hm["world_size"])
	_hm_data       = hm["data"]
	print("ParkLoader: heightmap loaded %d×%d" % [_hm_width, _hm_depth])


func _terrain_y(x: float, z: float) -> float:
	## Sample the heightmap at world (x, z). Returns 0.0 if no heightmap.
	if _hm_data.is_empty():
		return 0.0
	var half := _hm_world_size * 0.5
	var xi   := (x + half) / _hm_world_size * (_hm_width  - 1)
	var zi   := (z + half) / _hm_world_size * (_hm_depth  - 1)
	var xi0  := clampi(int(xi), 0, _hm_width  - 2)
	var zi0  := clampi(int(zi), 0, _hm_depth  - 2)
	var fx   := xi - xi0
	var fz   := zi - zi0
	var h00  := float(_hm_data[zi0       * _hm_width + xi0    ])
	var h10  := float(_hm_data[zi0       * _hm_width + xi0 + 1])
	var h01  := float(_hm_data[(zi0 + 1) * _hm_width + xi0    ])
	var h11  := float(_hm_data[(zi0 + 1) * _hm_width + xi0 + 1])
	return h00*(1.0-fx)*(1.0-fz) + h10*fx*(1.0-fz) + h01*(1.0-fx)*fz + h11*fx*fz


# ---------------------------------------------------------------------------
func _ready() -> void:
	if not FileAccess.file_exists(DATA_PATH):
		push_warning("ParkLoader: park_data.json not found – run convert_to_godot.py first")
		return

	_load_heightmap()

	var fa   := FileAccess.open(DATA_PATH, FileAccess.READ)
	var data  = JSON.parse_string(fa.get_as_text())
	fa.close()

	if typeof(data) != TYPE_DICTIONARY:
		push_error("ParkLoader: failed to parse park_data.json")
		return

	print("ParkLoader: building path meshes…")
	_build_buildings(data.get("buildings", []))
	_build_paths(data.get("paths", []))
	_build_water(data.get("water", []))
	_build_labels(data.get("water", []))
	_build_trees(data.get("trees", []))
	_build_boundary(data.get("boundary", []))
	print("ParkLoader: done")


# ---------------------------------------------------------------------------
# Path meshes – one MeshInstance3D per highway type
# ---------------------------------------------------------------------------
func _build_paths(paths: Array) -> void:
	var ground_groups: Dictionary = {}
	var bridge_paths:  Array      = []
	var tunnel_paths:  Array      = []

	for path in paths:
		var hw:    String = str(path.get("highway", "path"))
		var surf:  String = str(path.get("surface", ""))
		var layer: int    = int(path.get("layer",   0))
		var is_bridge: bool = bool(path.get("bridge", false)) or layer >= 1
		var is_tunnel: bool = bool(path.get("tunnel", false)) or layer <= -1

		if is_bridge:
			bridge_paths.append(path)
		elif is_tunnel:
			tunnel_paths.append(path)
		else:
			var key: String = hw + "|" + surf
			if key not in ground_groups:
				ground_groups[key] = []
			ground_groups[key].append(path)

	for key in ground_groups:
		var parts: PackedStringArray = key.split("|")
		add_child(_make_path_mesh(ground_groups[key], str(parts[0]), str(parts[1])))

	# Collect bridge centroids so tunnels can detect if they're an underpass
	var bridge_centroids: Array = []
	for bp in bridge_paths:
		var bpts: Array = bp["points"]
		var cx := 0.0; var cz := 0.0
		for pt in bpts:
			cx += float(pt[0]); cz += float(pt[2])
		cx /= bpts.size(); cz /= bpts.size()
		bridge_centroids.append(Vector2(cx, cz))

	for bp in bridge_paths:
		_build_bridge(bp)

	for tp in tunnel_paths:
		# Check if this tunnel is near a bridge (= underpass, not a rock tunnel)
		var tpts: Array = tp["points"]
		var tcx := 0.0; var tcz := 0.0
		for pt in tpts:
			tcx += float(pt[0]); tcz += float(pt[2])
		tcx /= tpts.size(); tcz /= tpts.size()
		var near_bridge := false
		for bc in bridge_centroids:
			if Vector2(tcx, tcz).distance_to(bc) < 60.0:
				near_bridge = true
				break
		if near_bridge:
			# Render as normal ground-level path (bridge overhead provides cover)
			var hw_t:   String = str(tp.get("highway", "path"))
			var surf_t: String = str(tp.get("surface", ""))
			var key_t: String = hw_t + "|" + surf_t
			add_child(_make_path_mesh([tp], hw_t, surf_t))
		else:
			_build_tunnel(tp)


func _make_path_mesh(paths: Array, hw: String, surface: String) -> MeshInstance3D:
	var verts   := PackedVector3Array()
	var normals := PackedVector3Array()
	var uvs     := PackedVector2Array()
	var width   := _hw_width(hw)

	for path in paths:
		var pts: Array = path["points"]
		var u := 0.0
		for i in range(pts.size() - 1):
			var x1 := float(pts[i][0]);   var z1 := float(pts[i][2])
			var x2 := float(pts[i+1][0]); var z2 := float(pts[i+1][2])
			var p1 := Vector3(x1, _terrain_y(x1, z1), z1)
			var p2 := Vector3(x2, _terrain_y(x2, z2), z2)
			var seg2 := Vector2(p2.x - p1.x, p2.z - p1.z)
			if seg2.length_squared() < 0.0001:
				continue
			var seg_len := seg2.length()
			var d  := seg2 / seg_len
			var n  := Vector2(-d.y, d.x)
			var hw2 := width * 0.5
			var a  := Vector3(p1.x + n.x * hw2,  p1.y + PATH_Y,  p1.z + n.y * hw2)
			var b  := Vector3(p1.x - n.x * hw2,  p1.y + PATH_Y,  p1.z - n.y * hw2)
			var c  := Vector3(p2.x + n.x * hw2,  p2.y + PATH_Y,  p2.z + n.y * hw2)
			var dd := Vector3(p2.x - n.x * hw2,  p2.y + PATH_Y,  p2.z - n.y * hw2)
			var quad_n := (b - a).cross(c - a).normalized()
			if quad_n.y < 0.0:
				quad_n = -quad_n
			var u2 := u + seg_len / width
			verts.append_array(PackedVector3Array([a, b, c, b, dd, c]))
			for _i in range(6):
				normals.append(quad_n)
			uvs.append_array(PackedVector2Array([
				Vector2(u, 0.0), Vector2(u, 1.0), Vector2(u2, 0.0),
				Vector2(u, 1.0), Vector2(u2, 1.0), Vector2(u2, 0.0),
			]))
			u = u2

	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_TEX_UV] = uvs

	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	mesh.surface_set_material(0, _make_path_material(hw, surface))

	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.name = "Paths_" + hw + ("_" + surface if surface else "")
	return mi


# ---------------------------------------------------------------------------
# Bridge geometry
# A bridge path is lifted to a fixed clearance above the lowest terrain point
# in its span, then gets:
#   • a textured deck ribbon (same width as the path)
#   • thin parapet boxes along each side (0.15 m thick, 0.9 m tall)
#   • vertical abutment quads at each end connecting deck to terrain
# ---------------------------------------------------------------------------
const BRIDGE_CLEARANCE := 3.5   # metres above lowest span terrain (room to walk under)
const BRIDGE_DECK_T    := 0.4   # deck thickness (visible from below)
const PARAPET_H        := 0.9   # parapet wall height above deck
const PARAPET_T        := 0.15  # parapet thickness
const BRIDGE_RAMP_FRAC := 0.35  # fraction of bridge path used as ramp at each end
const TUNNEL_H         := 3.4   # clear height inside tunnel (metres above path)

func _subdivide_pts(pts: Array, max_seg: float) -> Array:
	## Ensure no segment exceeds max_seg metres by inserting linearly interpolated points.
	var out: Array = [pts[0]]
	for i in range(1, pts.size()):
		var ax := float(pts[i-1][0]); var ay := float(pts[i-1][1]); var az := float(pts[i-1][2])
		var bx := float(pts[i][0]);   var by := float(pts[i][1]);   var bz := float(pts[i][2])
		var dx := bx - ax; var dz := bz - az
		var seg := sqrt(dx*dx + dz*dz)
		var n_sub := int(ceil(seg / max_seg))
		for j in range(1, n_sub + 1):
			var t := float(j) / float(n_sub)
			out.append([ax + dx * t, ay + (by - ay) * t, az + dz * t])
	return out


func _build_bridge(path: Dictionary) -> void:
	var hw:   String = str(path.get("highway", "path"))
	var surf: String = str(path.get("surface", ""))
	var raw_pts: Array = path["points"]
	if raw_pts.size() < 2:
		return

	# Subdivide so we have at least 1 point per ~2 metres for smooth ramps.
	var pts: Array = _subdivide_pts(raw_pts, 2.0)
	# Snap Y to actual terrain so bridge clearance is computed from the rendered surface
	for i in range(pts.size()):
		pts[i] = [pts[i][0], _terrain_y(float(pts[i][0]), float(pts[i][2])), pts[i][2]]
	var n_pts := pts.size()

	var width := _hw_width(hw)
	var hw2   := width * 0.5

	# CC0 rock wall texture for parapets / abutments
	var rw_alb := _load_tex("res://textures/rock_wall_diff.jpg")
	var rw_nrm := _load_tex("res://textures/rock_wall_nrm.jpg")
	var rw_rgh := _load_tex("res://textures/rock_wall_rgh.jpg")

	# ----------------------------------------------------------------
	# Cumulative arc lengths
	# ----------------------------------------------------------------
	var cum_len := PackedFloat32Array()
	cum_len.resize(n_pts)
	cum_len[0] = 0.0
	for i in range(1, n_pts):
		var dx := float(pts[i][0]) - float(pts[i-1][0])
		var dz := float(pts[i][2]) - float(pts[i-1][2])
		cum_len[i] = cum_len[i-1] + sqrt(dx*dx + dz*dz)
	var total_len := cum_len[n_pts - 1]
	if total_len < 0.1:
		return
	var ramp_len := total_len * BRIDGE_RAMP_FRAC

	# Terrain heights at the two endpoints
	var y_start := float(pts[0][1])
	var y_end   := float(pts[n_pts - 1][1])

	# Deck clearance: scale with bridge length
	#   Short bridges (< 10m): stream crossings, ~0.8m rise (gentle hump)
	#   Medium (10-25m):  scale linearly 0.8 → 3.5m
	#   Long (> 25m):     full 3.5m clearance (pedestrian underpass height)
	var eff_clearance: float
	if total_len < 10.0:
		eff_clearance = 0.8
	elif total_len < 25.0:
		eff_clearance = lerpf(0.8, BRIDGE_CLEARANCE, (total_len - 10.0) / 15.0)
	else:
		eff_clearance = BRIDGE_CLEARANCE

	var min_y_mid := INF
	for i in range(n_pts):
		if cum_len[i] >= ramp_len and cum_len[i] <= total_len - ramp_len:
			min_y_mid = minf(min_y_mid, float(pts[i][1]))
	if min_y_mid == INF:
		min_y_mid = y_start
		for pt in pts:
			min_y_mid = minf(min_y_mid, float(pt[1]))
	var deck_y := maxf(min_y_mid + eff_clearance,
					   maxf(y_start + 0.5, y_end + 0.5))

	# ----------------------------------------------------------------
	# Per-point smooth bridge height (S-curve ramp at both ends)
	# ----------------------------------------------------------------
	var pt_y := PackedFloat32Array()
	pt_y.resize(n_pts)
	for i in range(n_pts):
		var d := cum_len[i]
		var t: float
		var y: float
		if d <= ramp_len:
			t = d / ramp_len
			t = t * t * (3.0 - 2.0 * t)   # smoothstep
			y = lerpf(y_start + PATH_Y, deck_y, t)
		elif d >= total_len - ramp_len:
			t = (total_len - d) / ramp_len
			t = t * t * (3.0 - 2.0 * t)   # smoothstep
			y = lerpf(y_end + PATH_Y, deck_y, t)
		else:
			y = deck_y
		pt_y[i] = y

	# ----------------------------------------------------------------
	# Deck ribbon (UV-mapped along path)
	# ----------------------------------------------------------------
	var verts   := PackedVector3Array()
	var normals := PackedVector3Array()
	var uvs     := PackedVector2Array()
	var u := 0.0

	for i in range(n_pts - 1):
		var p1 := Vector3(float(pts[i][0]),     pt_y[i],     float(pts[i][2]))
		var p2 := Vector3(float(pts[i+1][0]),   pt_y[i+1],   float(pts[i+1][2]))
		var seg2 := Vector2(p2.x - p1.x, p2.z - p1.z)
		if seg2.length_squared() < 0.0001:
			continue
		var seg_len := seg2.length()
		var dv := seg2 / seg_len
		var nv := Vector2(-dv.y, dv.x)
		var a  := Vector3(p1.x + nv.x * hw2, p1.y, p1.z + nv.y * hw2)
		var b  := Vector3(p1.x - nv.x * hw2, p1.y, p1.z - nv.y * hw2)
		var c  := Vector3(p2.x + nv.x * hw2, p2.y, p2.z + nv.y * hw2)
		var dd := Vector3(p2.x - nv.x * hw2, p2.y, p2.z - nv.y * hw2)
		var u2 := u + seg_len / width
		verts.append_array(PackedVector3Array([a, b, c, b, dd, c]))
		var quad_n := (b - a).cross(c - a).normalized()
		if quad_n.y < 0.0:
			quad_n = -quad_n
		for _i in range(6):
			normals.append(quad_n)
		uvs.append_array(PackedVector2Array([
			Vector2(u, 0.0), Vector2(u, 1.0), Vector2(u2, 0.0),
			Vector2(u, 1.0), Vector2(u2, 1.0), Vector2(u2, 0.0),
		]))
		u = u2

	if not verts.is_empty():
		var arrays: Array = []
		arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = verts
		arrays[Mesh.ARRAY_NORMAL] = normals
		arrays[Mesh.ARRAY_TEX_UV] = uvs
		var deck_mesh := ArrayMesh.new()
		deck_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		deck_mesh.surface_set_material(0, _make_path_material(hw, surf))
		var deck_mi := MeshInstance3D.new()
		deck_mi.mesh = deck_mesh
		deck_mi.name = "Bridge_Deck"
		add_child(deck_mi)

		# Walkable collision from deck triangles
		var body  := StaticBody3D.new()
		body.name  = "Bridge_Collision"
		var shape := ConcavePolygonShape3D.new()
		shape.set_faces(verts)
		var col   := CollisionShape3D.new()
		col.shape  = shape
		body.add_child(col)
		add_child(body)

	# ----------------------------------------------------------------
	# Soffit (underside of deck) — only on bridges tall enough to walk under
	# ----------------------------------------------------------------
	var sof_verts   := PackedVector3Array()
	var sof_normals := PackedVector3Array()
	var sof_uvs     := PackedVector2Array()
	var _skip_soffit := total_len < 12.0
	var edge_verts  := PackedVector3Array()
	var edge_norms  := PackedVector3Array()
	var u_s := 0.0
	var sof_ramp_start := ramp_len * 0.15
	var sof_ramp_end   := total_len - ramp_len * 0.15

	for i in range(n_pts - 1):
		if _skip_soffit:
			break
		# Only build soffit/edges where bridge is elevated
		if cum_len[i + 1] < sof_ramp_start or cum_len[i] > sof_ramp_end:
			continue
		var p1 := Vector3(float(pts[i][0]),     pt_y[i],     float(pts[i][2]))
		var p2 := Vector3(float(pts[i+1][0]),   pt_y[i+1],   float(pts[i+1][2]))
		var seg2 := Vector2(p2.x - p1.x, p2.z - p1.z)
		if seg2.length_squared() < 0.0001:
			continue
		var seg_len := seg2.length()
		var dv := seg2 / seg_len
		var nv := Vector2(-dv.y, dv.x)
		var bot1 := p1.y - BRIDGE_DECK_T
		var bot2 := p2.y - BRIDGE_DECK_T
		# Soffit quad (downward-facing, reversed winding)
		var sa := Vector3(p1.x + nv.x * hw2, bot1, p1.z + nv.y * hw2)
		var sb := Vector3(p1.x - nv.x * hw2, bot1, p1.z - nv.y * hw2)
		var sc := Vector3(p2.x + nv.x * hw2, bot2, p2.z + nv.y * hw2)
		var sd := Vector3(p2.x - nv.x * hw2, bot2, p2.z - nv.y * hw2)
		var u2_s := u_s + seg_len / width
		sof_verts.append_array(PackedVector3Array([sa, sb, sc, sb, sd, sc]))
		for _j in range(6):
			sof_normals.append(Vector3.DOWN)
		sof_uvs.append_array(PackedVector2Array([
			Vector2(u_s, 0.0), Vector2(u_s, 1.0), Vector2(u2_s, 0.0),
			Vector2(u_s, 1.0), Vector2(u2_s, 1.0), Vector2(u2_s, 0.0),
		]))
		# Side edge beams (deck top to soffit bottom, both sides)
		for side in [-1.0, 1.0]:
			var s: float = float(side)
			var ox := nv.x * hw2 * s
			var oz := nv.y * hw2 * s
			var ea := Vector3(p1.x + ox, p1.y,  p1.z + oz)
			var eb := Vector3(p2.x + ox, p2.y,  p2.z + oz)
			var ec := Vector3(p2.x + ox, bot2,  p2.z + oz)
			var ed := Vector3(p1.x + ox, bot1,  p1.z + oz)
			edge_verts.append_array(PackedVector3Array([ea, eb, ec, ea, ec, ed]))
			var en := Vector3(nv.x * s, 0.0, nv.y * s)
			for _j in range(6):
				edge_norms.append(en)
		u_s = u2_s

	if not sof_verts.is_empty():
		sof_verts.append_array(edge_verts)
		sof_normals.append_array(edge_norms)
		# UVs for edges not critical — extend soffit UVs array to match
		for _j in range(edge_verts.size()):
			sof_uvs.append(Vector2.ZERO)
		var sof_arrays: Array = []; sof_arrays.resize(Mesh.ARRAY_MAX)
		sof_arrays[Mesh.ARRAY_VERTEX] = sof_verts
		sof_arrays[Mesh.ARRAY_NORMAL] = sof_normals
		sof_arrays[Mesh.ARRAY_TEX_UV] = sof_uvs
		var sof_mesh := ArrayMesh.new()
		sof_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, sof_arrays)
		sof_mesh.surface_set_material(0, _make_stone_material(rw_alb, rw_nrm, rw_rgh,
				Color(0.78, 0.76, 0.72)))
		var sof_mi := MeshInstance3D.new()
		sof_mi.mesh = sof_mesh
		sof_mi.name = "Bridge_Soffit"
		add_child(sof_mi)

	# ----------------------------------------------------------------
	# Parapet walls (rock_wall texture) — only on bridges long enough for an
	# elevated span. Short stream crossings (< 12m) skip parapets entirely.
	# ----------------------------------------------------------------
	var par_verts   := PackedVector3Array()
	var par_normals := PackedVector3Array()
	var par_ramp_start := ramp_len * 0.3
	var par_ramp_end   := total_len - ramp_len * 0.3
	var _skip_parapets := total_len < 12.0

	if not _skip_parapets:
		for i in range(n_pts - 1):
			# Skip segments fully within the ramp approach (no parapets there)
			if cum_len[i + 1] < par_ramp_start or cum_len[i] > par_ramp_end:
				continue
			var p1 := Vector3(float(pts[i][0]),     pt_y[i],     float(pts[i][2]))
			var p2 := Vector3(float(pts[i+1][0]),   pt_y[i+1],   float(pts[i+1][2]))
			var seg2 := Vector2(p2.x - p1.x, p2.z - p1.z)
			if seg2.length_squared() < 0.0001:
				continue
			var dv  := seg2.normalized()
			var nv  := Vector2(-dv.y, dv.x)
			var ohw := hw2 + PARAPET_T
			for side in [-1.0, 1.0]:
				var s: float = float(side)
				var ox := nv.x * ohw * s
				var oz := nv.y * ohw * s
				var fa := Vector3(p1.x + ox, p1.y,              p1.z + oz)
				var fb := Vector3(p2.x + ox, p2.y,              p2.z + oz)
				var fc := Vector3(p2.x + ox, p2.y + PARAPET_H,  p2.z + oz)
				var fd := Vector3(p1.x + ox, p1.y + PARAPET_H,  p1.z + oz)
				par_verts.append_array(PackedVector3Array([fa, fb, fc, fa, fc, fd]))
				var wall_n := Vector3(nv.x * s, 0.0, nv.y * s)
				for _j in range(6):
					par_normals.append(wall_n)

	if not par_verts.is_empty():
		var par_arrays: Array = []
		par_arrays.resize(Mesh.ARRAY_MAX)
		par_arrays[Mesh.ARRAY_VERTEX] = par_verts
		par_arrays[Mesh.ARRAY_NORMAL] = par_normals
		var par_mesh := ArrayMesh.new()
		par_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, par_arrays)
		par_mesh.surface_set_material(0, _make_stone_material(rw_alb, rw_nrm, rw_rgh,
				Color(0.82, 0.80, 0.76)))
		var par_mi := MeshInstance3D.new()
		par_mi.mesh = par_mesh
		par_mi.name = "Bridge_Parapets"
		add_child(par_mi)

	# ----------------------------------------------------------------
	# Abutment wing walls — only on bridges with real underpasses (>= 15m)
	# ----------------------------------------------------------------
	var abut_verts   := PackedVector3Array()
	var abut_normals := PackedVector3Array()
	var span_start_i := -1
	var span_end_i   := -1
	if total_len >= 15.0:
		for i in range(n_pts):
			if cum_len[i] >= ramp_len and span_start_i < 0:
				span_start_i = i
			if cum_len[i] <= total_len - ramp_len:
				span_end_i = i

	if span_start_i >= 0 and span_end_i >= 0:
		for end_i in [span_start_i, span_end_i]:
			var px   := float(pts[end_i][0])
			var pz   := float(pts[end_i][2])
			var ty   := float(pts[end_i][1])   # terrain level
			var dy   := pt_y[end_i]             # deck level
			if dy - ty < 0.5:
				continue   # not enough gap for a visible abutment

			# Get path direction at this point for the abutment face orientation
			var other_i: int = (end_i + 1) if end_i == span_start_i else (end_i - 1)
			other_i = clampi(other_i, 0, n_pts - 1)
			var seg2 := Vector2(float(pts[other_i][0]) - px,
								float(pts[other_i][2]) - pz)
			if seg2.length_squared() < 0.01:
				continue
			var dv  := seg2.normalized()
			var nv  := Vector2(-dv.y, dv.x)
			var face_dir := -1.0 if end_i == span_start_i else 1.0
			var face_n   := Vector3(dv.x * face_dir, 0.0, dv.y * face_dir)
			var ohw      := hw2 + PARAPET_T + 0.3   # slightly wider than parapets
			var lintel_h := 0.4   # stone lintel depth at top of opening

			# Wing walls: one on each side of the opening, from hw2 outward to ohw
			for side in [-1.0, 1.0]:
				var s: float = float(side)
				# Wing wall: from path edge to outer edge, terrain to deck
				var wa := Vector3(px + nv.x * hw2 * s, ty,  pz + nv.y * hw2 * s)
				var wb := Vector3(px + nv.x * ohw * s, ty,  pz + nv.y * ohw * s)
				var wc := Vector3(px + nv.x * ohw * s, dy,  pz + nv.y * ohw * s)
				var wd := Vector3(px + nv.x * hw2 * s, dy,  pz + nv.y * hw2 * s)
				abut_verts.append_array(PackedVector3Array([wa, wb, wc, wa, wc, wd]))
				for _j in range(6):
					abut_normals.append(face_n)

			# Lintel across the top of the opening (deck bottom to deck, full width)
			var lt_y := dy - lintel_h
			var la := Vector3(px + nv.x * hw2, lt_y, pz + nv.y * hw2)
			var lb := Vector3(px - nv.x * hw2, lt_y, pz - nv.y * hw2)
			var lc := Vector3(px - nv.x * hw2, dy,   pz - nv.y * hw2)
			var ld := Vector3(px + nv.x * hw2, dy,   pz + nv.y * hw2)
			abut_verts.append_array(PackedVector3Array([la, lb, lc, la, lc, ld]))
			for _j in range(6):
				abut_normals.append(face_n)

	if not abut_verts.is_empty():
		var abut_arrays: Array = []; abut_arrays.resize(Mesh.ARRAY_MAX)
		abut_arrays[Mesh.ARRAY_VERTEX] = abut_verts
		abut_arrays[Mesh.ARRAY_NORMAL] = abut_normals
		var abut_mesh := ArrayMesh.new()
		abut_mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, abut_arrays)
		abut_mesh.surface_set_material(0, _make_stone_material(rw_alb, rw_nrm, rw_rgh,
				Color(0.80, 0.78, 0.74)))
		var abut_mi := MeshInstance3D.new()
		abut_mi.mesh = abut_mesh
		abut_mi.name = "Bridge_Abutments"
		add_child(abut_mi)


# ---------------------------------------------------------------------------
# Tunnel geometry — ceiling ribbon + side walls + floor path
# ---------------------------------------------------------------------------
func _build_tunnel(path: Dictionary) -> void:
	var hw:   String = str(path.get("highway", "path"))
	var surf: String = str(path.get("surface", ""))
	var pts:  Array  = path["points"]
	if pts.size() < 2:
		return
	# Snap Y to rendered terrain surface
	for i in range(pts.size()):
		pts[i] = [pts[i][0], _terrain_y(float(pts[i][0]), float(pts[i][2])), pts[i][2]]

	var width := _hw_width(hw)
	var hw2   := width * 0.5

	# CC0 concrete texture for ceiling / walls
	var cw_alb := _load_tex("res://textures/concrete_wall_diff.jpg")
	var cw_nrm := _load_tex("res://textures/concrete_wall_nrm.jpg")
	var cw_rgh := _load_tex("res://textures/concrete_wall_rgh.jpg")
	var tun_mat := _make_stone_material(cw_alb, cw_nrm, cw_rgh, Color(0.72, 0.71, 0.70))

	var ceil_verts   := PackedVector3Array()
	var ceil_normals := PackedVector3Array()
	var ceil_uvs     := PackedVector2Array()
	var wall_verts   := PackedVector3Array()
	var wall_normals := PackedVector3Array()
	var wall_uvs     := PackedVector2Array()
	var u_c := 0.0
	var u_w := 0.0

	# Floor is lowered by TUNNEL_H so the ceiling ends up flush with terrain level.
	# This puts the tunnel underground where it belongs.
	for i in range(pts.size() - 1):
		var fy1 := float(pts[i][1])   + PATH_Y - TUNNEL_H
		var fy2 := float(pts[i+1][1]) + PATH_Y - TUNNEL_H
		var p1  := Vector3(float(pts[i][0]),   fy1, float(pts[i][2]))
		var p2  := Vector3(float(pts[i+1][0]), fy2, float(pts[i+1][2]))
		var seg2 := Vector2(p2.x - p1.x, p2.z - p1.z)
		if seg2.length_squared() < 0.0001:
			continue
		var seg_len := seg2.length()
		var dv  := seg2 / seg_len
		var nv  := Vector2(-dv.y, dv.x)
		var cy1 := p1.y + TUNNEL_H   # ≈ original terrain y — ceiling at grade
		var cy2 := p2.y + TUNNEL_H

		# Ceiling (downward-facing, sits at terrain level)
		var ca := Vector3(p1.x + nv.x * hw2, cy1, p1.z + nv.y * hw2)
		var cb := Vector3(p1.x - nv.x * hw2, cy1, p1.z - nv.y * hw2)
		var cc := Vector3(p2.x + nv.x * hw2, cy2, p2.z + nv.y * hw2)
		var cd := Vector3(p2.x - nv.x * hw2, cy2, p2.z - nv.y * hw2)
		var u2_c := u_c + seg_len / width
		ceil_verts.append_array(PackedVector3Array([ca, cc, cb, cb, cc, cd]))
		for _i in range(6):
			ceil_normals.append(Vector3.DOWN)
		ceil_uvs.append_array(PackedVector2Array([
			Vector2(u_c, 0.0), Vector2(u2_c, 0.0), Vector2(u_c,  1.0),
			Vector2(u_c, 1.0), Vector2(u2_c, 0.0), Vector2(u2_c, 1.0),
		]))
		u_c = u2_c

		# Side walls (inward-facing, floor to ceiling)
		var u2_w := u_w + seg_len / TUNNEL_H
		for side in [-1.0, 1.0]:
			var s: float = float(side)
			var ox := nv.x * hw2 * s
			var oz := nv.y * hw2 * s
			var wa := Vector3(p1.x + ox, p1.y, p1.z + oz)
			var wb := Vector3(p2.x + ox, p2.y, p2.z + oz)
			var wc := Vector3(p2.x + ox, cy2,  p2.z + oz)
			var wd := Vector3(p1.x + ox, cy1,  p1.z + oz)
			var wall_n := Vector3(-nv.x * s, 0.0, -nv.y * s)
			wall_verts.append_array(PackedVector3Array([wa, wb, wc, wa, wc, wd]))
			for _j in range(6):
				wall_normals.append(wall_n)
			wall_uvs.append_array(PackedVector2Array([
				Vector2(u_w,  0.0), Vector2(u2_w, 0.0), Vector2(u2_w, 1.0),
				Vector2(u_w,  0.0), Vector2(u2_w, 1.0), Vector2(u_w,  1.0),
			]))
		u_w = u2_w

	if not ceil_verts.is_empty():
		var arrays: Array = []; arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = ceil_verts
		arrays[Mesh.ARRAY_NORMAL] = ceil_normals
		arrays[Mesh.ARRAY_TEX_UV] = ceil_uvs
		var mesh := ArrayMesh.new()
		mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		mesh.surface_set_material(0, tun_mat)
		var mi := MeshInstance3D.new(); mi.mesh = mesh; mi.name = "Tunnel_Ceiling"
		add_child(mi)

	if not wall_verts.is_empty():
		var arrays: Array = []; arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = wall_verts
		arrays[Mesh.ARRAY_NORMAL] = wall_normals
		arrays[Mesh.ARRAY_TEX_UV] = wall_uvs
		var mesh := ArrayMesh.new()
		mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		mesh.surface_set_material(0, tun_mat)
		var mi := MeshInstance3D.new(); mi.mesh = mesh; mi.name = "Tunnel_Walls"
		add_child(mi)

	# Portal arches at each entrance/exit — stone arch framing the opening
	_build_tunnel_portals(pts, width, TUNNEL_H, tun_mat)

	# Floor surface at lowered depth
	var mod_path := path.duplicate()
	var mod_pts  := []
	for pt in pts:
		mod_pts.append([pt[0], float(pt[1]) - TUNNEL_H, pt[2]])
	mod_path["points"] = mod_pts
	var floor_mi := _make_path_mesh([mod_path], hw, surf)
	floor_mi.name = "Tunnel_Floor"
	add_child(floor_mi)


func _build_tunnel_portals(pts: Array, width: float, height: float, mat: Material) -> void:
	# Stone arch face at each end of the tunnel (entrance / exit)
	var hw2    := width * 0.5
	var n_steps := 8   # arch segments

	for end_i in [0, pts.size() - 1]:
		var other_i := 1 if end_i == 0 else pts.size() - 2
		var pe  := Vector3(float(pts[end_i][0]),   float(pts[end_i][1]),   float(pts[end_i][2]))
		var po  := Vector3(float(pts[other_i][0]), float(pts[other_i][1]), float(pts[other_i][2]))
		var seg2  := Vector2(po.x - pe.x, po.z - pe.z).normalized()
		# Outward normal of the portal face
		var face_n := -Vector3(seg2.x, 0.0, seg2.y)
		var right  := Vector2(-seg2.y, seg2.x)

		# Portal frame: bottom corners at lowered floor, arch crown at ceiling level
		var floor_y := pe.y + PATH_Y - height
		var ceil_y  := pe.y + PATH_Y           # ≈ terrain level

		var arch_verts   := PackedVector3Array()
		var arch_normals := PackedVector3Array()

		# Left and right vertical jambs (from floor to spring line = half height)
		var spring_y := floor_y + height * 0.5
		var arch_r   := hw2   # arch radius = half width

		for side in [-1.0, 1.0]:
			var s: float = float(side)
			var ox := right.x * hw2 * s
			var oz := right.y * hw2 * s
			# Jamb quad: floor → spring line
			var ja := Vector3(pe.x + ox, floor_y,  pe.z + oz)
			var jb := Vector3(pe.x + ox, spring_y, pe.z + oz)
			# Outer edge of jamb (slightly wider)
			var jao := Vector3(pe.x + right.x*(hw2 + 0.6)*s, floor_y,  pe.z + right.y*(hw2 + 0.6)*s)
			var jbo := Vector3(pe.x + right.x*(hw2 + 0.6)*s, spring_y, pe.z + right.y*(hw2 + 0.6)*s)
			arch_verts.append_array(PackedVector3Array([ja, jb, jbo, ja, jbo, jao]))
			for _j in range(6):
				arch_normals.append(face_n)

		# Semicircular arch from left spring to right spring
		for ai in range(n_steps):
			var a1 := PI * float(ai)     / float(n_steps)   # 0 → π (left→right)
			var a2 := PI * float(ai + 1) / float(n_steps)
			# Inner arch edge
			var ix1 := pe.x + right.x * (-cos(a1) * arch_r)
			var iz1 := pe.z + right.y * (-cos(a1) * arch_r)
			var iy1 := spring_y + sin(a1) * arch_r * 0.7   # slightly flattened
			var ix2 := pe.x + right.x * (-cos(a2) * arch_r)
			var iz2 := pe.z + right.y * (-cos(a2) * arch_r)
			var iy2 := spring_y + sin(a2) * arch_r * 0.7
			# Outer arch edge (0.6 m thick voussoir ring)
			var ox1 := pe.x + right.x * (-cos(a1) * (arch_r + 0.6))
			var oz1 := pe.z + right.y * (-cos(a1) * (arch_r + 0.6))
			var oy1 := spring_y + sin(a1) * (arch_r + 0.6) * 0.7
			var ox2 := pe.x + right.x * (-cos(a2) * (arch_r + 0.6))
			var oz2 := pe.z + right.y * (-cos(a2) * (arch_r + 0.6))
			var oy2 := spring_y + sin(a2) * (arch_r + 0.6) * 0.7
			var vi := Vector3(ix1, iy1, iz1); var vi2 := Vector3(ix2, iy2, iz2)
			var vo := Vector3(ox1, oy1, oz1); var vo2 := Vector3(ox2, oy2, oz2)
			arch_verts.append_array(PackedVector3Array([vi, vi2, vo2, vi, vo2, vo]))
			for _j in range(6):
				arch_normals.append(face_n)

		if not arch_verts.is_empty():
			var arrays: Array = []; arrays.resize(Mesh.ARRAY_MAX)
			arrays[Mesh.ARRAY_VERTEX] = arch_verts
			arrays[Mesh.ARRAY_NORMAL] = arch_normals
			var mesh := ArrayMesh.new()
			mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
			mesh.surface_set_material(0, mat)
			var mi := MeshInstance3D.new(); mi.mesh = mesh; mi.name = "Tunnel_Portal"
			add_child(mi)


# Shared helper: PBR stone/concrete material — uses world-space UV so no
# UV array is needed on the mesh (works on parapets, portals, walls, etc.)
func _make_stone_material(alb: ImageTexture, nrm: ImageTexture, rgh: ImageTexture,
						  tint: Color) -> Material:
	if alb:
		var sh  := Shader.new()
		sh.code  = _stone_shader_code()
		var sm  := ShaderMaterial.new()
		sm.shader = sh
		sm.set_shader_parameter("tex_alb", alb)
		sm.set_shader_parameter("tex_nrm", nrm)
		sm.set_shader_parameter("tex_rgh", rgh)
		sm.set_shader_parameter("tint",    tint)
		return sm
	var mat        := StandardMaterial3D.new()
	mat.albedo_color = tint
	mat.roughness    = 0.88
	mat.cull_mode    = BaseMaterial3D.CULL_DISABLED
	return mat


func _stone_shader_code() -> String:
	return """shader_type spatial;
render_mode cull_disabled;

uniform sampler2D tex_alb : source_color,      filter_linear_mipmap_anisotropic, repeat_enable;
uniform sampler2D tex_nrm : hint_normal,        filter_linear_mipmap_anisotropic, repeat_enable;
uniform sampler2D tex_rgh : hint_default_white, filter_linear_mipmap_anisotropic, repeat_enable;
uniform vec4 tint : source_color = vec4(1.0);

varying vec3 world_pos;
varying vec3 world_nrm;

void vertex() {
	world_pos = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
	world_nrm = normalize((MODEL_MATRIX * vec4(NORMAL, 0.0)).xyz);
}

void fragment() {
	// Triplanar UV: blend XZ (top/ceiling), XY (front/back), YZ (sides)
	vec3 blend = abs(world_nrm);
	blend = pow(blend, vec3(4.0));
	blend /= (blend.x + blend.y + blend.z + 0.001);
	float tile = 2.0;   // 2 m texture tile
	vec3 alb = texture(tex_alb, world_pos.xz / tile).rgb * blend.y
	         + texture(tex_alb, world_pos.xy / tile).rgb * blend.z
	         + texture(tex_alb, world_pos.yz / tile).rgb * blend.x;
	vec3 nrm = texture(tex_nrm, world_pos.xz / tile).rgb * blend.y
	         + texture(tex_nrm, world_pos.xy / tile).rgb * blend.z
	         + texture(tex_nrm, world_pos.yz / tile).rgb * blend.x;
	float rgh = texture(tex_rgh, world_pos.xz / tile).r * blend.y
	          + texture(tex_rgh, world_pos.xy / tile).r * blend.z
	          + texture(tex_rgh, world_pos.yz / tile).r * blend.x;
	ALBEDO     = alb * tint.rgb;
	NORMAL_MAP = nrm;
	ROUGHNESS  = clamp(rgh * 0.9 + 0.05, 0.0, 1.0);
	METALLIC   = 0.0;
}
"""


# ---------------------------------------------------------------------------
# Water bodies – filled polygons triangulated with Geometry2D
# ---------------------------------------------------------------------------
func _build_water(water: Array) -> void:
	if water.is_empty():
		return

	var verts   := PackedVector3Array()
	var normals := PackedVector3Array()

	for body in water:
		var pts: Array = body["points"]
		if pts.size() < 3:
			continue

		# Water level = minimum terrain height along the shore + small offset.
		# This ensures the water surface never floats above the surrounding terrain.
		var wy := INF
		for pt in pts:
			var hh := _terrain_y(float(pt[0]), float(pt[1]))
			wy = minf(wy, hh)
		wy += WATER_Y

		var polygon := PackedVector2Array()
		for pt in pts:
			polygon.append(Vector2(float(pt[0]), float(pt[1])))

		var indices := Geometry2D.triangulate_polygon(polygon)
		if indices.is_empty():
			continue

		for i in range(0, indices.size(), 3):
			verts.append(Vector3(polygon[indices[i    ]].x, wy, polygon[indices[i    ]].y))
			verts.append(Vector3(polygon[indices[i + 1]].x, wy, polygon[indices[i + 1]].y))
			verts.append(Vector3(polygon[indices[i + 2]].x, wy, polygon[indices[i + 2]].y))
			for _j in range(3):
				normals.append(Vector3.UP)

	if verts.is_empty():
		return

	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals

	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)

	var sh  := Shader.new()
	sh.code  = _water_shader_code()
	var mat := ShaderMaterial.new()
	mat.shader = sh
	mesh.surface_set_material(0, mat)

	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.name = "WaterBodies"
	add_child(mi)


func _water_shader_code() -> String:
	return """shader_type spatial;
render_mode cull_disabled;

varying vec3 world_pos;

// Gradient noise (returns -1..1)
vec2 ghash(vec2 p) {
	p = vec2(dot(p, vec2(127.1, 311.7)), dot(p, vec2(269.5, 183.3)));
	return fract(sin(p) * 43758.5453) * 2.0 - 1.0;
}
float gnoise(vec2 p) {
	vec2 i = floor(p); vec2 f = fract(p);
	vec2 u = f * f * (3.0 - 2.0 * f);
	return mix(mix(dot(ghash(i),          f),
	               dot(ghash(i+vec2(1,0)), f-vec2(1,0)), u.x),
	           mix(dot(ghash(i+vec2(0,1)), f-vec2(0,1)),
	               dot(ghash(i+vec2(1,1)), f-vec2(1,1)), u.x), u.y);
}

// World-space wave normal from two overlapping noise layers
vec3 wave_normal(vec2 uv) {
	float t  = TIME;
	vec2 o1  = vec2( t * 0.11,  t * 0.07);
	vec2 o2  = vec2(-t * 0.09,  t * 0.13);
	float e  = 0.05;
	// Height field: coarse + fine layer
	float h   = gnoise(uv       + o1) * 0.65 + gnoise(uv * 1.9       + o2) * 0.35;
	float hx  = gnoise(uv+vec2(e,0)+o1)*0.65 + gnoise((uv+vec2(e,0))*1.9+o2)*0.35;
	float hz  = gnoise(uv+vec2(0,e)+o1)*0.65 + gnoise((uv+vec2(0,e))*1.9+o2)*0.35;
	return normalize(vec3(-(hx - h) / e * 0.18, 1.0, -(hz - h) / e * 0.18));
}

void vertex() {
	world_pos = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
}

void fragment() {
	vec2 uv      = world_pos.xz / 7.0;   // wave tile ~7 m
	vec3 wave_nrm = wave_normal(uv);      // world-space

	// Wave height for colour modulation (-1..1)
	float wave_h = gnoise(uv + vec2(TIME * 0.11, TIME * 0.07));

	// Deep blue-grey ↔ lighter teal at crests
	vec3 deep    = vec3(0.04, 0.16, 0.34);
	vec3 shallow = vec3(0.10, 0.34, 0.58);
	vec3 col     = mix(deep, shallow, wave_h * 0.5 + 0.5);

	// Convert world-space normal → view-space for Godot lighting
	NORMAL    = normalize((VIEW_MATRIX * vec4(wave_nrm, 0.0)).xyz);
	ALBEDO    = col;
	ROUGHNESS = 0.04;   // very smooth — strong specular glint
	METALLIC  = 0.08;
	SPECULAR  = 1.0;    // PBR Fresnel gives edge reflectivity automatically
}
"""


# ---------------------------------------------------------------------------
# Buildings – extruded footprint polygons; walls + flat roofs batched separately
# ---------------------------------------------------------------------------
func _build_buildings(buildings: Array) -> void:
	if buildings.is_empty():
		return

	var wall_verts   := PackedVector3Array()
	var wall_normals := PackedVector3Array()
	var wall_uvs     := PackedVector2Array()
	var roof_verts   := PackedVector3Array()
	var roof_normals := PackedVector3Array()

	for bld in buildings:
		var pts:  Array = bld["points"]
		var h:    float = float(bld["height"])
		# Snap base to minimum terrain height across footprint so building
		# doesn't float above terrain on any side
		var base := INF
		for pt in pts:
			base = minf(base, _terrain_y(float(pt[0]), float(pt[1])))
		if base == INF:
			base = float(bld.get("base", 0.0))
		var top:  float = base + h
		var n:    int   = pts.size()
		if n < 3:
			continue

		# Walls – UV.x = metres along wall, UV.y = metres above base
		for i in n:
			var p1 := Vector2(float(pts[i][0]),           float(pts[i][1]))
			var p2 := Vector2(float(pts[(i + 1) % n][0]), float(pts[(i + 1) % n][1]))
			var seg := p2 - p1
			if seg.length_squared() < 0.01:
				continue
			var seg_len := seg.length()
			var norm := Vector3(-seg.y, 0.0, seg.x).normalized()
			var a := Vector3(p1.x, base, p1.y)
			var b := Vector3(p2.x, base, p2.y)
			var c := Vector3(p2.x, top,  p2.y)
			var d := Vector3(p1.x, top,  p1.y)
			wall_verts.append_array(PackedVector3Array([a, b, c, a, c, d]))
			for _j in range(6):
				wall_normals.append(norm)
			wall_uvs.append_array(PackedVector2Array([
				Vector2(0.0,     0.0),
				Vector2(seg_len, 0.0),
				Vector2(seg_len, h),
				Vector2(0.0,     0.0),
				Vector2(seg_len, h),
				Vector2(0.0,     h),
			]))

		# Flat roof
		var polygon := PackedVector2Array()
		for pt in pts:
			polygon.append(Vector2(float(pt[0]), float(pt[1])))
		var indices := Geometry2D.triangulate_polygon(polygon)
		for i in range(0, indices.size(), 3):
			roof_verts.append(Vector3(polygon[indices[i    ]].x, top, polygon[indices[i    ]].y))
			roof_verts.append(Vector3(polygon[indices[i + 1]].x, top, polygon[indices[i + 1]].y))
			roof_verts.append(Vector3(polygon[indices[i + 2]].x, top, polygon[indices[i + 2]].y))
			for _j in range(3):
				roof_normals.append(Vector3.UP)

	# Walls: facade shader with window grid
	if not wall_verts.is_empty():
		var arrays: Array = []; arrays.resize(Mesh.ARRAY_MAX)
		arrays[Mesh.ARRAY_VERTEX] = wall_verts
		arrays[Mesh.ARRAY_NORMAL] = wall_normals
		arrays[Mesh.ARRAY_TEX_UV] = wall_uvs
		var mesh := ArrayMesh.new()
		mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
		mesh.surface_set_material(0, _make_facade_material())
		var mi := MeshInstance3D.new(); mi.mesh = mesh; mi.name = "BuildingWalls"
		add_child(mi)

	_add_batch_mesh(roof_verts, roof_normals, Color(0.38, 0.36, 0.34), 0.92, "BuildingRoofs")


func _add_batch_mesh(verts: PackedVector3Array, normals: PackedVector3Array,
					 color: Color, roughness: float, node_name: String) -> void:
	if verts.is_empty():
		return
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	var mat := StandardMaterial3D.new()
	mat.albedo_color = color
	mat.roughness    = roughness
	mat.cull_mode    = BaseMaterial3D.CULL_DISABLED
	mesh.surface_set_material(0, mat)
	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.name = node_name
	add_child(mi)


# ---------------------------------------------------------------------------
# Building facade material + shader
# ---------------------------------------------------------------------------
func _make_facade_material() -> ShaderMaterial:
	var sh   := Shader.new()
	sh.code   = _facade_shader_code()
	var mat  := ShaderMaterial.new()
	mat.shader = sh
	return mat


func _facade_shader_code() -> String:
	return """shader_type spatial;
render_mode cull_disabled;

// Window grid dimensions (metres)
const float WIN_W  = 1.5;   // window width
const float WIN_H  = 2.0;   // window height
const float GAP_X  = 0.6;   // horizontal gap between windows
const float GAP_Y  = 0.8;   // floor-to-floor gap (sill + lintel)
const float GROUND = 3.5;   // metres of solid base before first windows

varying vec3 world_pos;

float hash2(vec2 p) {
	p = fract(p * vec2(127.1, 311.7));
	p += dot(p, p + 43.21);
	return fract(p.x * p.y);
}

void vertex() {
	world_pos = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
}

void fragment() {
	float cell_w = WIN_W + GAP_X;
	float cell_h = WIN_H + GAP_Y;

	// Local position within a window cell
	float lx = fract(UV.x / cell_w);
	float ly = fract((UV.y - GROUND) / cell_h);

	bool in_win = (lx < WIN_W / cell_w) && (ly < WIN_H / cell_h) && (UV.y > GROUND);

	// Building identity from snapped world position
	vec2 bld = floor(world_pos.xz * 0.03);
	// Style: 0 = limestone pre-war, 1 = glass tower
	float style = step(0.5, hash2(bld * 1.7));

	// Per-window light/glass variation
	vec2 cell = vec2(floor(UV.x / cell_w), floor((UV.y - GROUND) / cell_h));
	float wrand = hash2(bld * 0.5 + cell * 0.13);

	vec3 col;
	float rough;
	float metal = 0.0;

	if (in_win) {
		if (style < 0.5) {
			// Limestone: dark recess windows, slight warm tint
			vec3 dark_glass = vec3(0.10, 0.13, 0.16);
			vec3 refl_glass = vec3(0.35, 0.48, 0.58);
			col   = mix(dark_glass, refl_glass, wrand * 0.5);
			rough = 0.08;
			metal = 0.15;
		} else {
			// Glass tower: reflective blue-grey curtain wall
			vec3 g1 = vec3(0.28, 0.38, 0.52);
			vec3 g2 = vec3(0.48, 0.58, 0.70);
			col   = mix(g1, g2, wrand);
			rough = 0.04;
			metal = 0.35;
		}
	} else {
		// Wall surface
		float var_ = hash2(world_pos.xz * 0.15) * 0.10;
		if (style < 0.5) {
			// Warm limestone / granite
			col   = vec3(0.78, 0.72, 0.62) * (0.90 + var_);
			rough = 0.88;
		} else {
			// Cool aluminium spandrel panel
			col   = vec3(0.55, 0.58, 0.62) * (0.90 + var_);
			rough = 0.45;
			metal = 0.30;
		}
	}

	ALBEDO    = clamp(col, 0.0, 1.0);
	ROUGHNESS = rough;
	METALLIC  = metal;
}
"""


# ---------------------------------------------------------------------------
# Trees – crossed billboard planes, separate broadleaf/conifer MultiMeshes
# ---------------------------------------------------------------------------
func _build_trees(trees: Array) -> void:
	if trees.is_empty():
		return

	var rng := RandomNumberGenerator.new()

	# [trunk_h_min, trunk_h_max, trunk_r_min, trunk_r_max, canopy_sx, canopy_sy]
	var ap_table := [
		[15.0, 24.0, 0.28, 0.50, 1.55, 0.85],   # 0 oak
		[12.0, 18.0, 0.20, 0.36, 1.05, 1.05],   # 1 maple
		[20.0, 28.0, 0.18, 0.30, 0.70, 1.40],   # 2 elm
		[1.0,   3.5, 0.05, 0.12, 2.10, 0.45],   # 3 shrub
		[18.0, 32.0, 0.16, 0.26, 0.40, 2.30],   # 4 conifer
	]

	# Textures
	var broad_tex := _load_tex("res://textures/tree_canopy_broad.png")
	var conif_tex := _load_tex("res://textures/tree_canopy_conifer.png")
	var bark_alb  := _load_tex("res://textures/Bark007_1K-JPG_Color.jpg")
	var bark_nrm  := _load_tex("res://textures/Bark007_1K-JPG_NormalGL.jpg")
	var bark_rgh  := _load_tex("res://textures/Bark007_1K-JPG_Roughness.jpg")
	var bark_ao   := _load_tex("res://textures/Bark007_1K-JPG_AmbientOcclusion.jpg")

	# Shared canopy planes mesh (3 crossed vertical quads)
	var planes_mesh := _make_canopy_planes_mesh()

	# Canopy materials
	var broad_mat := _make_canopy_mat(broad_tex)
	var conif_mat := _make_canopy_mat(conif_tex)

	# Trunk mesh + material
	var trunk_mesh            := CylinderMesh.new()
	trunk_mesh.height          = 1.0
	trunk_mesh.top_radius      = 0.60
	trunk_mesh.bottom_radius   = 1.0
	trunk_mesh.radial_segments = 7

	var trunk_sh    := Shader.new()
	trunk_sh.code    = _trunk_shader_code()
	var trunk_mat   := ShaderMaterial.new()
	trunk_mat.shader = trunk_sh
	if bark_alb:
		trunk_mat.set_shader_parameter("bark_albedo", bark_alb)
		trunk_mat.set_shader_parameter("bark_normal",  bark_nrm)
		trunk_mat.set_shader_parameter("bark_rough",   bark_rgh)
		trunk_mat.set_shader_parameter("bark_ao",      bark_ao)

	# Collect transforms per group
	var broad_xf: Array = []
	var conif_xf: Array = []
	var trunk_xf: Array = []

	for i in trees.size():
		var pt: Array = trees[i]
		var tx := float(pt[0]); var tz := float(pt[2])
		var ty := _terrain_y(tx, tz)
		rng.seed = i * 1234567891 + 987654321

		var rv := rng.randf()
		var arch := 0
		if   rv < 0.35: arch = 0
		elif rv < 0.65: arch = 1
		elif rv < 0.85: arch = 2
		elif rv < 0.97: arch = 3
		else:           arch = 4

		var ap     : Array = ap_table[arch]
		var trunk_h := rng.randf_range(float(ap[0]), float(ap[1]))
		var trunk_r := rng.randf_range(float(ap[2]), float(ap[3]))
		var sx      := float(ap[4])
		var sy      := float(ap[5])
		var canopy_r := trunk_h * rng.randf_range(0.32, 0.56)

		var cbasis := Basis(
			Vector3(canopy_r * sx, 0.0,           0.0),
			Vector3(0.0,           canopy_r * sy, 0.0),
			Vector3(0.0,           0.0,           canopy_r * sx))
		var canopy_tf := Transform3D(cbasis, Vector3(tx, ty + trunk_h, tz))
		if arch == 4:
			conif_xf.append(canopy_tf)
		else:
			broad_xf.append(canopy_tf)

		var tbasis := Basis(
			Vector3(trunk_r, 0.0,     0.0),
			Vector3(0.0,     trunk_h, 0.0),
			Vector3(0.0,     0.0,     trunk_r))
		trunk_xf.append(Transform3D(tbasis, Vector3(tx, ty + trunk_h * 0.5, tz)))

	_spawn_multimesh(planes_mesh, broad_mat, broad_xf, "TreeCanopies_Broad")
	_spawn_multimesh(planes_mesh, conif_mat, conif_xf, "TreeCanopies_Conifer")
	_spawn_multimesh(trunk_mesh,  trunk_mat, trunk_xf, "TreeTrunks")
	_build_tree_collision(trunk_xf)


func _build_tree_collision(trunk_xf: Array) -> void:
	if trunk_xf.is_empty():
		return
	# One StaticBody3D with a CylinderShape3D per trunk.
	# trunk_xf basis encodes: x.x = trunk_r, y.y = trunk_h (see _build_trees).
	var body := StaticBody3D.new()
	body.name = "TreeTrunkCollision"
	for tf: Transform3D in trunk_xf:
		var r: float = tf.basis.x.x   # trunk_r
		var h: float = tf.basis.y.y   # trunk_h
		var shape        := CylinderShape3D.new()
		shape.radius      = r
		shape.height      = h
		var col          := CollisionShape3D.new()
		col.shape         = shape
		col.position      = tf.origin  # already at trunk centre (base + h/2)
		body.add_child(col)
	add_child(body)


func _make_canopy_planes_mesh() -> ArrayMesh:
	# 3 crossed vertical unit planes, 60° apart around Y axis
	var verts   := PackedVector3Array()
	var normals := PackedVector3Array()
	var uvs     := PackedVector2Array()
	var indices := PackedInt32Array()
	for pi in 3:
		var a  := PI * float(pi) / 3.0
		var c  := cos(a); var sa := sin(a)
		var base := verts.size()
		# corners: left-bottom, right-bottom, right-top, left-top
		verts.append_array(PackedVector3Array([
			Vector3(-c, -1.0, -sa),
			Vector3( c, -1.0,  sa),
			Vector3( c,  1.0,  sa),
			Vector3(-c,  1.0, -sa),
		]))
		# V=0 at top (y=+1), V=1 at bottom (y=-1) – matches texture orientation
		uvs.append_array(PackedVector2Array([
			Vector2(0.0, 1.0), Vector2(1.0, 1.0),
			Vector2(1.0, 0.0), Vector2(0.0, 0.0),
		]))
		var n := Vector3(-sa, 0.0, c)
		for _j in 4: normals.append(n)
		indices.append_array(PackedInt32Array([
			base, base+1, base+2, base, base+2, base+3,
		]))
	var arrays: Array = []; arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals
	arrays[Mesh.ARRAY_TEX_UV] = uvs
	arrays[Mesh.ARRAY_INDEX]  = indices
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	return mesh


func _make_canopy_mat(tex: ImageTexture) -> ShaderMaterial:
	var sh    := Shader.new()
	sh.code    = _canopy_shader_code()
	var mat   := ShaderMaterial.new()
	mat.shader = sh
	if tex:
		mat.set_shader_parameter("canopy_tex", tex)
	return mat


func _spawn_multimesh(mesh: Mesh, mat: Material,
					  transforms: Array, node_name: String) -> void:
	if transforms.is_empty():
		return
	var mm             := MultiMesh.new()
	mm.transform_format = MultiMesh.TRANSFORM_3D
	mm.mesh             = mesh
	mm.instance_count   = transforms.size()
	for i in transforms.size():
		mm.set_instance_transform(i, transforms[i])
	var mmi              := MultiMeshInstance3D.new()
	mmi.multimesh         = mm
	mmi.name              = node_name
	mmi.material_override = mat
	add_child(mmi)


func _canopy_shader_code() -> String:
	return """shader_type spatial;
render_mode cull_disabled, depth_prepass_alpha;

uniform sampler2D canopy_tex : source_color, filter_linear_mipmap_anisotropic;
uniform float alpha_cutoff = 0.18;

varying vec3 tree_origin;

float hash21(vec2 p) {
	p = fract(p * vec2(127.1, 311.7));
	p += dot(p, p + 43.21);
	return fract(p.x * p.y);
}

void vertex() {
	tree_origin = (MODEL_MATRIX * vec4(0.0, 0.0, 0.0, 1.0)).xyz;
	// Wind sway: phase from tree world position, weight by local height
	float sway = max(VERTEX.y, 0.0);
	VERTEX.x += sin(TIME * 0.7 + tree_origin.x * 0.04 + tree_origin.z * 0.06) * 0.09 * sway;
	VERTEX.z += sin(TIME * 1.1 + tree_origin.z * 0.05) * 0.05 * sway;
}

void fragment() {
	vec4 tex = texture(canopy_tex, UV);
	if (tex.a < alpha_cutoff) discard;

	// Per-tree colour variation from world position hash (no INSTANCE_CUSTOM needed)
	float h = hash21(floor(tree_origin.xz * 0.025));
	float bright = 0.72 + h * 0.44;
	float warm   = (h - 0.5) * 0.14;
	vec3 col = tex.rgb * bright;
	col.r += warm;
	col.b -= warm * 0.4;

	// Fake subsurface scattering: rim glows yellow-green (backlit leaves)
	float sss = pow(1.0 - max(dot(NORMAL, VIEW), 0.0), 3.0) * 0.20;
	col += vec3(0.09, 0.13, 0.01) * sss;

	ALBEDO    = clamp(col, 0.0, 1.0);
	ROUGHNESS = 0.88;
	METALLIC  = 0.0;
}
"""


func _trunk_shader_code() -> String:
	return """shader_type spatial;

uniform sampler2D bark_albedo : source_color,      filter_linear_mipmap_anisotropic, repeat_enable;
uniform sampler2D bark_normal : hint_normal,        filter_linear_mipmap_anisotropic, repeat_enable;
uniform sampler2D bark_rough  : hint_default_white, filter_linear_mipmap_anisotropic, repeat_enable;
uniform sampler2D bark_ao     : hint_default_white, filter_linear_mipmap_anisotropic, repeat_enable;

varying vec3 world_pos;

float hash21(vec2 p) {
	p = fract(p * vec2(127.1, 311.7));
	p += dot(p, p + 43.21);
	return fract(p.x * p.y);
}

void vertex() {
	world_pos = (MODEL_MATRIX * vec4(VERTEX, 1.0)).xyz;
}

void fragment() {
	vec2 uv   = vec2(UV.x * 2.0, UV.y * 4.0);
	vec3 alb  = texture(bark_albedo, uv).rgb;
	float rgh = texture(bark_rough,  uv).r;
	float ao  = texture(bark_ao,     uv).r;

	// Per-tree hue variation (dark brown ↔ grey-brown)
	float h = hash21(floor(world_pos.xz * 0.04));
	// Base brightness 0.30–0.48 (was 0.55–0.85) — much darker
	vec3 col = alb * ao * (0.30 + h * 0.18);
	// Warm brown push: boost red slightly, pull blue down
	col.r *= 1.08;
	col.b *= 0.82;

	ALBEDO     = clamp(col, 0.0, 1.0);
	NORMAL_MAP = texture(bark_normal, uv).rgb;
	ROUGHNESS  = clamp(rgh * 0.90 + 0.08, 0.0, 1.0);
	METALLIC   = 0.0;
}
"""


# ---------------------------------------------------------------------------
# POI name labels – billboard Label3D above each named water body
# ---------------------------------------------------------------------------
func _build_labels(water: Array) -> void:
	for body in water:
		var label_text: String = str(body.get("name", ""))
		if label_text.is_empty():
			continue
		var pts: Array = body["points"]
		if pts.is_empty():
			continue

		# Centroid and bounding-box diagonal for sizing
		var cx := 0.0
		var cz := 0.0
		var min_x :=  1e9; var max_x := -1e9
		var min_z :=  1e9; var max_z := -1e9
		for pt in pts:
			var px := float(pt[0]); var pz := float(pt[1])
			cx += px; cz += pz
			if px < min_x: min_x = px
			if px > max_x: max_x = px
			if pz < min_z: min_z = pz
			if pz > max_z: max_z = pz
		cx /= pts.size()
		cz /= pts.size()
		var diag := Vector2(max_x - min_x, max_z - min_z).length()

		# Taller label for larger features, clamped to a sensible range
		var height     := clampf(diag * 0.05, 8.0, 40.0)
		var pixel_size := clampf(diag * 0.00006, 0.03, 0.10)

		var lbl := Label3D.new()
		lbl.text              = label_text
		lbl.font_size         = 64
		lbl.pixel_size        = pixel_size
		lbl.billboard         = BaseMaterial3D.BILLBOARD_ENABLED
		lbl.modulate          = Color(1.0, 1.0, 1.0, 0.95)
		lbl.outline_size      = 8
		lbl.outline_modulate  = Color(0.0, 0.08, 0.25, 0.85)
		var water_y: float = float(body.get("water_y", 0.0))
		lbl.position          = Vector3(cx, water_y + height, cz)
		add_child(lbl)


func _append_quad(verts: PackedVector3Array, normals: PackedVector3Array,
				  p1: Vector3, p2: Vector3, width: float) -> void:
	var seg2 := Vector2(p2.x - p1.x, p2.z - p1.z)
	if seg2.length_squared() < 0.0001:
		return

	var d  := seg2.normalized()
	var n  := Vector2(-d.y, d.x)
	var hw := width * 0.5

	var a  := Vector3(p1.x + n.x * hw,  p1.y + PATH_Y,  p1.z + n.y * hw)
	var b  := Vector3(p1.x - n.x * hw,  p1.y + PATH_Y,  p1.z - n.y * hw)
	var c  := Vector3(p2.x + n.x * hw,  p2.y + PATH_Y,  p2.z + n.y * hw)
	var dd := Vector3(p2.x - n.x * hw,  p2.y + PATH_Y,  p2.z - n.y * hw)

	# Compute quad normal from actual geometry so sloped paths light correctly
	var quad_n := (b - a).cross(c - a).normalized()
	if quad_n.y < 0.0:
		quad_n = -quad_n

	verts.append_array(PackedVector3Array([a, b, c,   b, dd, c]))
	for _i in range(6):
		normals.append(quad_n)


# ---------------------------------------------------------------------------
# Boundary walls – invisible collision boxes along the park perimeter
# ---------------------------------------------------------------------------
func _build_boundary(boundary: Array) -> void:
	if boundary.size() < 3:
		push_warning("ParkLoader: boundary too small – skipping walls")
		return

	var body := StaticBody3D.new()
	body.name = "BoundaryWalls"
	add_child(body)

	var n := boundary.size()
	for i in range(n):
		var p1 := Vector2(float(boundary[i][0]),           float(boundary[i][1]))
		var p2 := Vector2(float(boundary[(i + 1) % n][0]), float(boundary[(i + 1) % n][1]))

		var seg_len := p1.distance_to(p2)
		if seg_len < 0.3:
			continue

		var mid := (p1 + p2) * 0.5
		var dir := (p2 - p1) / seg_len

		var box  := BoxShape3D.new()
		box.size  = Vector3(seg_len, 12.0, 0.5)

		var col      := CollisionShape3D.new()
		col.shape     = box
		col.position  = Vector3(mid.x, 6.0, mid.y)
		col.rotation.y = atan2(-dir.y, dir.x)

		body.add_child(col)
