extends Node3D
## Reads park_data.json (generated by convert_to_godot.py) and builds:
##   • One flat ribbon MeshInstance3D per highway type (batched for performance)
##   • One StaticBody3D with BoxShape3D collision per boundary segment (invisible walls)

const DATA_PATH := "res://park_data.json"
const PATH_Y    := 0.06   # metres above ground plane
const WATER_Y   := 0.03   # water sits above ground, below path ribbons


# ---------------------------------------------------------------------------
# Typed helpers – avoids Dictionary.get() returning Variant (parse error in 4.6)
# ---------------------------------------------------------------------------
func _hw_width(hw: String) -> float:
	match hw:
		"pedestrian": return 6.0
		"footway":    return 3.0
		"cycleway":   return 3.5
		"steps":      return 2.5
		"track":      return 3.0
		_:            return 2.5   # "path" and unknowns


func _path_color(hw: String, surface: String) -> Color:
	# Surface tag takes priority; highway type is the fallback
	match surface:
		"asphalt":            return Color(0.28, 0.28, 0.30)   # dark grey tarmac
		"concrete":           return Color(0.68, 0.68, 0.66)   # light grey concrete
		"concrete:plates":    return Color(0.65, 0.65, 0.63)   # concrete slabs
		"paving_stones":      return Color(0.78, 0.74, 0.65)   # cream/buff stone pavers
		"sett":               return Color(0.54, 0.52, 0.48)   # grey stone setts
		"unhewn_cobblestone": return Color(0.52, 0.50, 0.44)   # rough cobble
		"pebblestone":        return Color(0.60, 0.57, 0.50)   # pebble stone
		"stone":              return Color(0.60, 0.58, 0.54)   # cut stone
		"rock":               return Color(0.56, 0.54, 0.50)   # bare rock
		"brick":              return Color(0.68, 0.38, 0.26)   # brick red
		"metal":              return Color(0.62, 0.63, 0.66)   # steel grating
		"wood":               return Color(0.50, 0.34, 0.16)   # wooden boardwalk
		"paved":              return Color(0.60, 0.60, 0.58)   # generic paved
		"compacted":          return Color(0.52, 0.42, 0.28)   # compressed dirt/gravel
		"fine_gravel":        return Color(0.64, 0.57, 0.44)   # fine gravel
		"gravel":             return Color(0.60, 0.53, 0.40)   # loose gravel
		"unpaved":            return Color(0.54, 0.43, 0.28)   # unpaved dirt
		"dirt":               return Color(0.50, 0.38, 0.22)   # bare dirt
		"ground":             return Color(0.46, 0.38, 0.26)   # natural ground
		"grass":              return Color(0.28, 0.52, 0.18)   # grass path
		"woodchips":          return Color(0.46, 0.32, 0.14)   # woodchip mulch
		"mulch":              return Color(0.40, 0.28, 0.12)   # dark mulch
		"sand":               return Color(0.76, 0.70, 0.52)   # sand
	# Fallback to highway type
	match hw:
		"footway":    return Color(0.70, 0.64, 0.52)   # warm tan / gravel
		"cycleway":   return Color(0.30, 0.30, 0.32)   # asphalt (cycleways are almost always asphalt)
		"pedestrian": return Color(0.78, 0.74, 0.65)   # pale cream stone
		"path":       return Color(0.54, 0.44, 0.30)   # earthy dirt
		"steps":      return Color(0.60, 0.58, 0.54)   # grey stone
		"track":      return Color(0.48, 0.40, 0.26)   # brown dirt track
		_:            return Color(0.65, 0.60, 0.48)


# ---------------------------------------------------------------------------
func _ready() -> void:
	if not FileAccess.file_exists(DATA_PATH):
		push_warning("ParkLoader: park_data.json not found – run convert_to_godot.py first")
		return

	var fa   := FileAccess.open(DATA_PATH, FileAccess.READ)
	var data  = JSON.parse_string(fa.get_as_text())
	fa.close()

	if typeof(data) != TYPE_DICTIONARY:
		push_error("ParkLoader: failed to parse park_data.json")
		return

	print("ParkLoader: building path meshes…")
	_build_buildings(data.get("buildings", []))
	_build_paths(data.get("paths", []))
	_build_water(data.get("water", []))
	_build_labels(data.get("water", []))
	_build_trees(data.get("trees", []))
	_build_boundary(data.get("boundary", []))
	print("ParkLoader: done")


# ---------------------------------------------------------------------------
# Path meshes – one MeshInstance3D per highway type
# ---------------------------------------------------------------------------
func _build_paths(paths: Array) -> void:
	# Group by (highway, surface) so each material gets one batched mesh
	var groups: Dictionary = {}
	for path in paths:
		var hw:   String = str(path.get("highway", "path"))
		var surf: String = str(path.get("surface", ""))
		var key:  String = hw + "|" + surf
		if key not in groups:
			groups[key] = []
		groups[key].append(path)

	for key in groups:
		var parts := key.split("|")
		add_child(_make_path_mesh(groups[key], parts[0], parts[1]))


func _make_path_mesh(paths: Array, hw: String, surface: String) -> MeshInstance3D:
	var verts   := PackedVector3Array()
	var normals := PackedVector3Array()
	var width   := _hw_width(hw)

	for path in paths:
		var pts: Array = path["points"]
		for i in range(pts.size() - 1):
			# pts[i] is now [x, terrain_y, z]  (3 elements with terrain height)
			_append_quad(verts, normals,
				Vector3(float(pts[i][0]),     float(pts[i][1]),     float(pts[i][2])),
				Vector3(float(pts[i+1][0]),   float(pts[i+1][1]),   float(pts[i+1][2])),
				width)

	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals

	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)

	var mat := StandardMaterial3D.new()
	mat.albedo_color = _path_color(hw, surface)
	mat.roughness    = 0.85
	mat.cull_mode    = BaseMaterial3D.CULL_DISABLED

	mesh.surface_set_material(0, mat)

	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.name = "Paths_" + hw + ("_" + surface if surface else "")
	return mi


# ---------------------------------------------------------------------------
# Water bodies – filled polygons triangulated with Geometry2D
# ---------------------------------------------------------------------------
func _build_water(water: Array) -> void:
	if water.is_empty():
		return

	var verts   := PackedVector3Array()
	var normals := PackedVector3Array()

	for body in water:
		var pts: Array = body["points"]
		if pts.size() < 3:
			continue

		# water_y = terrain height at the body centroid (from convert_to_godot.py)
		var wy: float = float(body.get("water_y", 0.0)) + WATER_Y

		var polygon := PackedVector2Array()
		for pt in pts:
			polygon.append(Vector2(float(pt[0]), float(pt[1])))

		var indices := Geometry2D.triangulate_polygon(polygon)
		if indices.is_empty():
			continue

		for i in range(0, indices.size(), 3):
			verts.append(Vector3(polygon[indices[i    ]].x, wy, polygon[indices[i    ]].y))
			verts.append(Vector3(polygon[indices[i + 1]].x, wy, polygon[indices[i + 1]].y))
			verts.append(Vector3(polygon[indices[i + 2]].x, wy, polygon[indices[i + 2]].y))
			for _j in range(3):
				normals.append(Vector3.UP)

	if verts.is_empty():
		return

	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals

	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)

	var mat := StandardMaterial3D.new()
	mat.albedo_color = Color(0.13, 0.32, 0.62)
	mat.roughness    = 0.08
	mat.metallic     = 0.35
	mat.cull_mode    = BaseMaterial3D.CULL_DISABLED

	mesh.surface_set_material(0, mat)

	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.name = "WaterBodies"
	add_child(mi)


# ---------------------------------------------------------------------------
# Buildings – extruded footprint polygons; walls + flat roofs batched separately
# ---------------------------------------------------------------------------
func _build_buildings(buildings: Array) -> void:
	if buildings.is_empty():
		return

	var wall_verts   := PackedVector3Array()
	var wall_normals := PackedVector3Array()
	var roof_verts   := PackedVector3Array()
	var roof_normals := PackedVector3Array()

	for bld in buildings:
		var pts:  Array = bld["points"]
		var h:    float = float(bld["height"])
		var base: float = float(bld.get("base", 0.0))   # terrain height at centroid
		var top:  float = base + h
		var n:    int   = pts.size()
		if n < 3:
			continue

		# Walls – one quad per polygon edge, grounded at terrain height
		for i in n:
			var p1 := Vector2(float(pts[i][0]),           float(pts[i][1]))
			var p2 := Vector2(float(pts[(i + 1) % n][0]), float(pts[(i + 1) % n][1]))
			var seg := p2 - p1
			if seg.length_squared() < 0.01:
				continue
			var norm := Vector3(-seg.y, 0.0, seg.x).normalized()
			var a := Vector3(p1.x, base, p1.y)
			var b := Vector3(p2.x, base, p2.y)
			var c := Vector3(p2.x, top,  p2.y)
			var d := Vector3(p1.x, top,  p1.y)
			wall_verts.append_array(PackedVector3Array([a, b, c, a, c, d]))
			for _j in range(6):
				wall_normals.append(norm)

		# Flat roof at terrain_base + building_height
		var polygon := PackedVector2Array()
		for pt in pts:
			polygon.append(Vector2(float(pt[0]), float(pt[1])))
		var indices := Geometry2D.triangulate_polygon(polygon)
		for i in range(0, indices.size(), 3):
			roof_verts.append(Vector3(polygon[indices[i    ]].x, top, polygon[indices[i    ]].y))
			roof_verts.append(Vector3(polygon[indices[i + 1]].x, top, polygon[indices[i + 1]].y))
			roof_verts.append(Vector3(polygon[indices[i + 2]].x, top, polygon[indices[i + 2]].y))
			for _j in range(3):
				roof_normals.append(Vector3.UP)

	_add_batch_mesh(wall_verts, wall_normals, Color(0.76, 0.70, 0.62), 0.82, "BuildingWalls")
	_add_batch_mesh(roof_verts, roof_normals, Color(0.48, 0.46, 0.44), 0.88, "BuildingRoofs")


func _add_batch_mesh(verts: PackedVector3Array, normals: PackedVector3Array,
					 color: Color, roughness: float, node_name: String) -> void:
	if verts.is_empty():
		return
	var arrays: Array = []
	arrays.resize(Mesh.ARRAY_MAX)
	arrays[Mesh.ARRAY_VERTEX] = verts
	arrays[Mesh.ARRAY_NORMAL] = normals
	var mesh := ArrayMesh.new()
	mesh.add_surface_from_arrays(Mesh.PRIMITIVE_TRIANGLES, arrays)
	var mat := StandardMaterial3D.new()
	mat.albedo_color = color
	mat.roughness    = roughness
	mat.cull_mode    = BaseMaterial3D.CULL_DISABLED
	mesh.surface_set_material(0, mat)
	var mi := MeshInstance3D.new()
	mi.mesh = mesh
	mi.name = node_name
	add_child(mi)


# ---------------------------------------------------------------------------
# Trees – two MultiMeshInstance3D nodes (trunks + canopies) for one draw call each
# ---------------------------------------------------------------------------
func _build_trees(trees: Array) -> void:
	if trees.is_empty():
		return

	var count := trees.size()
	var rng   := RandomNumberGenerator.new()

	# Trunk: low-poly cylinder, brown
	var trunk_mesh            := CylinderMesh.new()
	trunk_mesh.height          = 5.0
	trunk_mesh.top_radius      = 0.12
	trunk_mesh.bottom_radius   = 0.20
	trunk_mesh.radial_segments = 6
	var trunk_mat              := StandardMaterial3D.new()
	trunk_mat.albedo_color      = Color(0.32, 0.20, 0.09)
	trunk_mat.roughness         = 0.95
	trunk_mesh.surface_set_material(0, trunk_mat)

	var trunk_mm              := MultiMesh.new()
	trunk_mm.mesh              = trunk_mesh
	trunk_mm.transform_format  = MultiMesh.TRANSFORM_3D
	trunk_mm.instance_count    = count

	# Canopy: low-poly sphere, green
	var canopy_mesh            := SphereMesh.new()
	canopy_mesh.radius          = 3.0
	canopy_mesh.height          = 6.0
	canopy_mesh.radial_segments = 8
	canopy_mesh.rings           = 5
	var canopy_mat             := StandardMaterial3D.new()
	canopy_mat.albedo_color     = Color(0.18, 0.44, 0.14)
	canopy_mat.roughness        = 0.90
	canopy_mesh.surface_set_material(0, canopy_mat)

	var canopy_mm             := MultiMesh.new()
	canopy_mm.mesh             = canopy_mesh
	canopy_mm.transform_format = MultiMesh.TRANSFORM_3D
	canopy_mm.instance_count   = count

	for i in count:
		var pt    := trees[i]
		var tx    := float(pt[0])
		var ty    := float(pt[1])   # terrain height baked in by convert_to_godot.py
		var tz    := float(pt[2])
		rng.seed   = i
		var scale := rng.randf_range(0.70, 1.35)
		var basis  := Basis.IDENTITY.scaled(Vector3(scale, scale, scale))
		trunk_mm.set_instance_transform(i,  Transform3D(basis, Vector3(tx, ty + scale * 2.5, tz)))
		canopy_mm.set_instance_transform(i, Transform3D(basis, Vector3(tx, ty + scale * 6.5, tz)))

	var trunk_mmi        := MultiMeshInstance3D.new()
	trunk_mmi.multimesh   = trunk_mm
	trunk_mmi.name        = "TreeTrunks"
	add_child(trunk_mmi)

	var canopy_mmi       := MultiMeshInstance3D.new()
	canopy_mmi.multimesh  = canopy_mm
	canopy_mmi.name       = "TreeCanopies"
	add_child(canopy_mmi)


# ---------------------------------------------------------------------------
# POI name labels – billboard Label3D above each named water body
# ---------------------------------------------------------------------------
func _build_labels(water: Array) -> void:
	for body in water:
		var label_text: String = str(body.get("name", ""))
		if label_text.is_empty():
			continue
		var pts: Array = body["points"]
		if pts.is_empty():
			continue

		# Centroid and bounding-box diagonal for sizing
		var cx := 0.0
		var cz := 0.0
		var min_x :=  1e9; var max_x := -1e9
		var min_z :=  1e9; var max_z := -1e9
		for pt in pts:
			var px := float(pt[0]); var pz := float(pt[1])
			cx += px; cz += pz
			if px < min_x: min_x = px
			if px > max_x: max_x = px
			if pz < min_z: min_z = pz
			if pz > max_z: max_z = pz
		cx /= pts.size()
		cz /= pts.size()
		var diag := Vector2(max_x - min_x, max_z - min_z).length()

		# Taller label for larger features, clamped to a sensible range
		var height     := clampf(diag * 0.05, 8.0, 40.0)
		var pixel_size := clampf(diag * 0.00006, 0.03, 0.10)

		var lbl := Label3D.new()
		lbl.text              = label_text
		lbl.font_size         = 64
		lbl.pixel_size        = pixel_size
		lbl.billboard         = BaseMaterial3D.BILLBOARD_ENABLED
		lbl.modulate          = Color(1.0, 1.0, 1.0, 0.95)
		lbl.outline_size      = 8
		lbl.outline_modulate  = Color(0.0, 0.08, 0.25, 0.85)
		var water_y: float = float(body.get("water_y", 0.0))
		lbl.position          = Vector3(cx, water_y + height, cz)
		add_child(lbl)


func _append_quad(verts: PackedVector3Array, normals: PackedVector3Array,
				  p1: Vector3, p2: Vector3, width: float) -> void:
	var seg2 := Vector2(p2.x - p1.x, p2.z - p1.z)
	if seg2.length_squared() < 0.0001:
		return

	var d  := seg2.normalized()
	var n  := Vector2(-d.y, d.x)
	var hw := width * 0.5

	var a  := Vector3(p1.x + n.x * hw,  p1.y + PATH_Y,  p1.z + n.y * hw)
	var b  := Vector3(p1.x - n.x * hw,  p1.y + PATH_Y,  p1.z - n.y * hw)
	var c  := Vector3(p2.x + n.x * hw,  p2.y + PATH_Y,  p2.z + n.y * hw)
	var dd := Vector3(p2.x - n.x * hw,  p2.y + PATH_Y,  p2.z - n.y * hw)

	# Compute quad normal from actual geometry so sloped paths light correctly
	var quad_n := (b - a).cross(c - a).normalized()
	if quad_n.y < 0.0:
		quad_n = -quad_n

	verts.append_array(PackedVector3Array([a, b, c,   b, dd, c]))
	for _i in range(6):
		normals.append(quad_n)


# ---------------------------------------------------------------------------
# Boundary walls – invisible collision boxes along the park perimeter
# ---------------------------------------------------------------------------
func _build_boundary(boundary: Array) -> void:
	if boundary.size() < 3:
		push_warning("ParkLoader: boundary too small – skipping walls")
		return

	var body := StaticBody3D.new()
	body.name = "BoundaryWalls"
	add_child(body)

	var n := boundary.size()
	for i in range(n):
		var p1 := Vector2(float(boundary[i][0]),           float(boundary[i][1]))
		var p2 := Vector2(float(boundary[(i + 1) % n][0]), float(boundary[(i + 1) % n][1]))

		var seg_len := p1.distance_to(p2)
		if seg_len < 0.3:
			continue

		var mid := (p1 + p2) * 0.5
		var dir := (p2 - p1) / seg_len

		var box  := BoxShape3D.new()
		box.size  = Vector3(seg_len, 12.0, 0.5)

		var col      := CollisionShape3D.new()
		col.shape     = box
		col.position  = Vector3(mid.x, 6.0, mid.y)
		col.rotation.y = atan2(-dir.y, dir.x)

		body.add_child(col)
